// src/shared/ui/AsyncContent.jsx
import Page from '@/layout/Page'
import LoadingState from '@/shared/ui/LoadingState'
import ErrorState from '@/shared/ui/ErrorState'
import OfflineState from '@/shared/ui/OfflineState'
import { useOnline } from '@/shared/hooks/useOnline'

// Renders the loading / offline / error states around an async page, so views
// only have to describe their happy path.
export default function AsyncContent({
  pending = false,
  error = null,
  loadingMessage,
  errorMessage = 'حدث خطأ أثناء تحميل البيانات، برجاء المحاولة في وقت لاحق.',
  children,
}) {
  const online = useOnline()

  if (pending) {
    return (
      <Page>
        <LoadingState message={loadingMessage} />
      </Page>
    )
  }

  if (error) {
    return <Page>{online ? <ErrorState code={500} message={errorMessage} /> : <OfflineState />}</Page>
  }

  return children
}

// src/shared/ui/AsyncContent.vue
<script setup>
import { useOnline } from '@vueuse/core'
import Page from '@/layout/Page.vue'
import LoadingState from '@/shared/ui/LoadingState.vue'
import ErrorState from '@/shared/ui/ErrorState.vue'
import OfflineState from '@/shared/ui/OfflineState.vue'

defineProps({
  pending: { type: Boolean, default: false },
  error: { type: [Object, Error], default: null },
  loadingMessage: { type: String, default: undefined },
  errorMessage: { type: String, default: 'حدث خطأ أثناء تحميل البيانات، برجاء المحاولة في وقت لاحق.' },
})

const online = useOnline()
</script>

<template>
  <Page v-if="pending">
    <LoadingState :message="loadingMessage" />
  </Page>

  <Page v-else-if="error">
    <OfflineState v-if="!online" />
    <ErrorState v-else :code="500" :message="errorMessage" />
  </Page>

  <slot v-else />
</template>
