// src/shared/ui/BackButton.jsx
import { Link } from 'react-router-dom'

export default function BackButton({ to, label = 'العودة', buttonClass = 'btn-flat', embedHidden = true }) {
  return (
    <Link
      to={to}
      className={`btn d-inline-flex align-items-center gap-2 ${buttonClass} ${embedHidden ? 'embed-hidden' : ''}`}
    >
      <span>{label}</span>
    </Link>
  )
}

// src/shared/ui/BackButton.vue
<script setup>
defineProps({
  to: {
    type: [String, Object],
    required: true,
  },
  label: {
    type: String,
    default: 'العودة',
  },
  buttonClass: {
    type: [String, Array, Object],
    default: 'btn-flat',
  },
  embedHidden: {
    type: Boolean,
    default: true,
  },
})
</script>

<template>
  <RouterLink
    :to="to"
    class="btn d-inline-flex align-items-center gap-2"
    :class="[buttonClass, { 'embed-hidden': embedHidden }]"
  >
    <span>{{ label }}</span>
  </RouterLink>
</template>
