// src/shared/ui/FavoriteList.jsx
import { IconHeart, IconHeartFilled } from '@tabler/icons-react'
import { useFavorites } from '@/shared/hooks/useFavorites'
import EmptyState from '@/shared/ui/EmptyState'
import styles from './FavoriteList.module.scss'

const noClass = () => ''

/**
 * A list whose entries can be favorited. Favorites are pinned to a second list
 * above the full one, which is hidden while a search is active.
 */
export default function FavoriteList({
  items,
  search = '',
  itemKey,
  favoritesKey,
  itemClass = noClass,
  favoritesTitle = null,
  allTitle = null,
  renderItem,
  renderActions,
}) {
  const { isFavorite, toggleFavorite, filterFavorites } = useFavorites(favoritesKey)

  const getKey = (item) => item[itemKey]
  const favorites = filterFavorites(items, getKey)
  const showFavorites = favorites.length > 0 && !search

  const renderRow = (item, index, favorited) => (
    <li key={getKey(item)} className={`list-group-item list-group-item-action py-3 ${itemClass(item)}`}>
      <div className="d-flex justify-content-between align-items-center">
        {renderItem?.(item, index)}

        <div className="d-flex gap-2">
          <button
            className="btn btn-flat position-relative z-1"
            onClick={() => toggleFavorite(getKey(item))}
            title={favorited ? 'إزالة من المفضلة' : 'إضافة للمفضلة'}
          >
            {favorited ? <IconHeartFilled size="1.25rem" className="text-danger" /> : <IconHeart size="1.25rem" />}
          </button>

          {renderActions?.(item)}
        </div>
      </div>
    </li>
  )

  return (
    <div className={styles.list}>
      {showFavorites && (
        <div className="mb-4">
          {favoritesTitle}
          <ul className="list-group">{favorites.map((item, index) => renderRow(item, index, true))}</ul>
        </div>
      )}

      {showFavorites && allTitle}

      <ul className="list-group">
        {items.map((item, index) => renderRow(item, index, isFavorite(getKey(item))))}

        {items.length === 0 && (
          <li className="list-group-item">
            <EmptyState />
          </li>
        )}
      </ul>
    </div>
  )
}

// src/shared/ui/FavoriteList.vue
<script setup>
import { computed } from 'vue'
import { IconHeart, IconHeartFilled } from '@tabler/icons-vue'
import { useFavorites } from '@/shared/composables/useFavorites'
import EmptyState from '@/shared/ui/EmptyState.vue'

const props = defineProps({
  items: {
    type: Array,
    required: true,
  },
  search: {
    type: String,
    default: '',
  },
  itemKey: {
    type: String,
    required: true,
  },
  favoritesKey: {
    type: String,
    required: true,
  },
  itemClass: {
    type: Function,
    default: () => ({}),
  },
})

const { isFavorite, toggleFavorite, filterFavorites } = useFavorites(props.favoritesKey)

const getKey = (item) => item[props.itemKey]
const favorites = filterFavorites(
  () => props.items,
  (item) => getKey(item),
)
</script>

<template>
  <div v-if="favorites.length && !search" class="mb-4">
    <slot name="favorites-title" />
    <ul class="list-group">
      <li
        v-for="(item, index) in favorites"
        :key="getKey(item)"
        class="list-group-item list-group-item-action py-3"
        :class="itemClass(item)"
      >
        <div class="d-flex justify-content-between align-items-center">
          <slot :item="item" :index="index" />

          <div class="d-flex gap-2">
            <button
              class="btn btn-flat position-relative z-1"
              @click.stop="toggleFavorite(getKey(item))"
              title="إزالة من المفضلة"
            >
              <IconHeartFilled size="1.25rem" class="text-danger" />
            </button>

            <slot name="actions" :item="item" />
          </div>
        </div>
      </li>
    </ul>
  </div>

  <slot v-if="favorites.length && !search" name="all-title" />
  <ul class="list-group">
    <li
      v-for="(item, index) in items"
      :key="getKey(item)"
      class="list-group-item list-group-item-action py-3"
      :class="itemClass(item)"
    >
      <div class="d-flex justify-content-between align-items-center">
        <slot :item="item" :index="index" />

        <div class="d-flex gap-2">
          <button
            class="btn btn-flat position-relative z-1"
            @click.stop="toggleFavorite(getKey(item))"
            :title="isFavorite(getKey(item)) ? 'إزالة من المفضلة' : 'إضافة للمفضلة'"
          >
            <IconHeartFilled v-if="isFavorite(getKey(item))" size="1.25rem" class="text-danger" />
            <IconHeart v-else size="1.25rem" />
          </button>

          <slot name="actions" :item="item" />
        </div>
      </div>
    </li>

    <li v-if="items.length === 0" class="list-group-item">
      <EmptyState />
    </li>
  </ul>
</template>

<style lang="scss" scoped>
.list-group-item:hover {
  background-color: rgba(var(--bs-secondary-rgb), 0.1);
}
</style>
