// src/shared/ui/LoadingState.vue
<script setup>
defineProps({
  message: {
    type: String,
    default: 'جاري التحميل...',
  },
})
</script>

<template>
  <div class="d-flex flex-column align-items-center justify-content-center gap-4">
    <div class="spinner-border" role="status">
      <span class="visually-hidden">جاري التحميل...</span>
    </div>

    <p class="lead">{{ message }}</p>
  </div>
</template>

// src/shared/ui/LoadingState.jsx
export default function LoadingState({ message = 'جاري التحميل...' }) {
  return (
    <div className="d-flex flex-column align-items-center justify-content-center gap-4">
      <div className="spinner-border" role="status">
        <span className="visually-hidden">جاري التحميل...</span>
      </div>

      <p className="lead">{message}</p>
    </div>
  )
}
