// src/features/azkar/components/ZekrCard.vue
<script setup>
import { ref } from 'vue'
import { onLongPress } from '@vueuse/core'
import { IconDownload, IconShare3, IconCopy, IconHeartShare, IconRestore } from '@tabler/icons-vue'
import { exportComponent } from '@/shared/utils/export'
import { toast } from 'vue-sonner'
import { toArabicNumerals } from '@/shared/utils/arabic'
import { useIsMobile } from '@/shared/composables/useIsMobile'
import { useZekrScroll } from '@/features/azkar/composables/useZekrScroll'
import { useZekrVibration } from '@/features/azkar/composables/useZekrVibration'

import ZekrImage from './ZekrImage.vue'

const props = defineProps({
  text: {
    type: String,
    required: true,
  },
  repeat: {
    type: Number,
    default: 1,
  },
  reference: {
    type: String,
  },
  benefit: {
    type: String,
  },
})

const emit = defineEmits(['increment', 'reset'])

const count = ref(0)
const card = ref(null)
const isMobile = useIsMobile()
const { vibrateOnFinish } = useZekrVibration()
const { scrollToNextZekr } = useZekrScroll(card)

const increment = () => {
  if (count.value < props.repeat) {
    count.value++
    emit('increment')

    if (count.value === props.repeat) {
      vibrateOnFinish()
      scrollToNextZekr()
    }
  }
}

const reset = () => {
  if (count.value > 0) {
    emit('reset', count.value)
    count.value = 0
  }
}

// On mobile a long press often doesn't emit a trailing `click`, so it wouldn't
// be counted. We catch it explicitly with `onLongPress` below. When the browser
// *does* fire a click after the press, this guard swallows it so the same press
// isn't counted twice.
let longPressHandled = false

const handleLongPress = (event) => {
  if (!isMobile.value) return
  // Let the action menu handle its own presses (open dropdown, not count).
  if (event?.target?.closest?.('.action-menu')) return

  longPressHandled = true
  increment()
}

const consumeLongPress = () => {
  if (longPressHandled) {
    longPressHandled = false
    return true
  }
  return false
}

const onCardClick = () => {
  if (!isMobile.value) return
  if (consumeLongPress()) return
  increment()
}

const onCounterClick = () => {
  if (consumeLongPress()) return
  increment()
}

onLongPress(card, handleLongPress, {
  delay: 500,
  // Clear the guard shortly after release in case no trailing click arrives,
  // so the next genuine tap still counts.
  onMouseUp: () => setTimeout(() => (longPressHandled = false), 100),
})

const exportAsImage = () => {
  toast.promise(
    async () => {
      await new Promise((resolve) => setTimeout(resolve, 1000))
      return exportComponent(ZekrImage, props, 'zekr')
    },
    {
      loading: 'جاري التصدير...',
      success: 'تم تصدير الصورة بنجاح',
      error: 'حدث خطأ أثناء تصدير الصورة',
    },
  )
}

const shareZekr = () => {
  toast.promise(() => navigator.share({ title: 'رفيق', text: props.text }), {
    loading: 'جاري المشاركة...',
    success: 'تم مشاركة الذكر بنجاح',
    error: 'حدث خطأ أثناء مشاركة الذكر',
  })
}

const copyZekr = () => {
  toast.promise(() => navigator.clipboard.writeText(props.text), {
    loading: 'جاري النسخ...',
    success: 'تم نسخ الذكر بنجاح',
    error: 'حدث خطأ أثناء نسخ الذكر',
  })
}
</script>

<template>
  <div ref="card" class="zekr-card border rounded p-4" @click="onCardClick">
    <div class="action-menu dropdown" @click.stop>
      <button class="btn p-0 bg-transparent" type="button" data-bs-toggle="dropdown">
        <IconHeartShare size="18" />
      </button>

      <ul class="dropdown-menu dropdown-menu-end">
        <li>
          <button class="dropdown-item d-flex align-items-center gap-2" @click="exportAsImage">
            <IconDownload size="18" />
            <span>تنزيل</span>
          </button>
        </li>
        <li>
          <button class="dropdown-item d-flex align-items-center gap-2" @click="shareZekr">
            <IconShare3 size="18" />
            <span>مشاركة</span>
          </button>
        </li>
        <li>
          <button class="dropdown-item d-flex align-items-center gap-2" @click="copyZekr">
            <IconCopy size="18" />
            <span>نسخ</span>
          </button>
        </li>
        <li><hr class="dropdown-divider" /></li>
        <li>
          <button class="dropdown-item d-flex align-items-center gap-2" :disabled="count === 0" @click="reset">
            <IconRestore size="18" />
            <span>تصفير</span>
          </button>
        </li>
      </ul>
    </div>

    <div class="row align-items-center g-4 text-center text-lg-start">
      <div class="col-12 col-lg-auto">
        <button
          class="btn btn-counter border-flat"
          @click.stop="onCounterClick"
          :style="{ '--progress': count / repeat }"
          :data-content="toArabicNumerals(`${count}/${repeat}`)"
        ></button>
      </div>

      <div class="col-12 col-lg">
        <p class="zekr-text font-quran m-0">{{ text }}</p>

        <p class="text-muted m-0 pe-2" v-if="benefit || reference">
          <small v-if="reference">{{ reference }}</small>
          <small v-if="benefit && reference"> - </small>
          <small v-if="benefit">{{ benefit }}</small>
        </p>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.zekr-card {
  position: relative;

  .btn-counter {
    position: relative;
    border-radius: 50%;
    /* rem (not px) so the progress circle scales with the font and the
       counter text (e.g. "100/100") stays centered without overflowing. */
    width: 7.5rem;
    height: 7.5rem;
    font-size: 1.25rem;
    border: none;

    background:
      radial-gradient(closest-side, var(--bs-body-bg) 79%, transparent 80% 100%),
      conic-gradient(var(--bs-primary) calc(var(--progress) * 100%), rgba(var(--bs-secondary-rgb), 0.1) 0);

    &::before {
      content: attr(data-content);
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
    }
  }

  .zekr-text {
    text-align: justify;
    font-size: 1.625rem;
    line-height: 2;
  }

  .action-menu {
    position: absolute;
    inset-inline-end: 0.5rem;
    inset-block-end: 0.5rem;

    [data-bs-toggle='dropdown'] {
      width: 30px;
      height: 30px;
      display: grid;
      place-items: center;
      color: var(--bs-secondary);
    }
  }
}

@media screen and (max-width: 992px) {
  .zekr-card {
    cursor: pointer;
    user-select: none;

    > .row {
      flex-direction: column-reverse;
    }
  }
}
</style>

// src/features/azkar/components/ZekrCard.jsx
import { useRef } from 'react'
import { IconDownload, IconShare3, IconCopy, IconHeartShare, IconRestore } from '@tabler/icons-react'
import { toast } from 'sonner'

import ZekrImage from './ZekrImage'
import { useZekrScroll } from '@/features/azkar/hooks/useZekrScroll'
import { useZekrVibration } from '@/features/azkar/hooks/useZekrVibration'
import { useIsMobile } from '@/shared/hooks/useIsMobile'
import { useLongPress } from '@/shared/hooks/useLongPress'
import { exportElement } from '@/shared/utils/export'
import { toArabicNumerals } from '@/shared/utils/arabic'
import styles from './ZekrCard.module.scss'

// Counting targets: the counter button and the action menu handle their own
// clicks, so a tap anywhere else on the card counts instead.
const IGNORED_TARGETS = '[data-zekr-counter], [data-zekr-actions]'

export default function ZekrCard({ text, repeat = 1, reference, benefit, count = 0, onCountChange, className = '' }) {
  const cardRef = useRef(null)
  const isMobile = useIsMobile()
  const { vibrateOnFinish } = useZekrVibration()
  const { scrollToNextZekr } = useZekrScroll(cardRef)

  // A long press already counted, so the click it may emit afterwards must not.
  const longPressed = useRef(false)

  const increment = () => {
    if (count >= repeat) return

    const next = count + 1
    onCountChange?.(next)

    if (next === repeat) {
      vibrateOnFinish()
      scrollToNextZekr()
    }
  }

  const reset = () => {
    if (count > 0) onCountChange?.(0)
  }

  useLongPress(
    cardRef,
    (event) => {
      if (!isMobile || event.target.closest(IGNORED_TARGETS)) return
      longPressed.current = true
      increment()
    },
    // Mobile long presses often emit no click at all, so clear the flag shortly
    // after release in case none arrives.
    { onRelease: () => setTimeout(() => (longPressed.current = false), 100) },
  )

  const handleCardClick = () => {
    if (isMobile && !longPressed.current) increment()
    longPressed.current = false
  }

  const exportAsImage = () => {
    toast.promise(
      async () => {
        await new Promise((resolve) => setTimeout(resolve, 1000))
        return exportElement(<ZekrImage text={text} repeat={repeat} reference={reference} benefit={benefit} />, 'zekr')
      },
      {
        loading: 'جاري التصدير...',
        success: 'تم تصدير الصورة بنجاح',
        error: 'حدث خطأ أثناء تصدير الصورة',
      },
    )
  }

  const shareZekr = () => {
    toast.promise(() => navigator.share({ title: 'رفيق', text }), {
      loading: 'جاري المشاركة...',
      success: 'تم مشاركة الذكر بنجاح',
      error: 'حدث خطأ أثناء مشاركة الذكر',
    })
  }

  const copyZekr = () => {
    toast.promise(() => navigator.clipboard.writeText(text), {
      loading: 'جاري النسخ...',
      success: 'تم نسخ الذكر بنجاح',
      error: 'حدث خطأ أثناء نسخ الذكر',
    })
  }

  return (
    <div
      ref={cardRef}
      data-zekr-card
      className={`${styles.card} border rounded p-4 ${className}`}
      onClick={handleCardClick}
    >
      <div data-zekr-actions className={`${styles.actions} dropdown`} onClick={(event) => event.stopPropagation()}>
        <button className="btn p-0 bg-transparent" type="button" data-bs-toggle="dropdown" aria-label="خيارات الذكر">
          <IconHeartShare size="18" />
        </button>

        <ul className="dropdown-menu dropdown-menu-end">
          <li>
            <button className="dropdown-item d-flex align-items-center gap-2" onClick={exportAsImage}>
              <IconDownload size="18" />
              <span>تنزيل</span>
            </button>
          </li>
          <li>
            <button className="dropdown-item d-flex align-items-center gap-2" onClick={shareZekr}>
              <IconShare3 size="18" />
              <span>مشاركة</span>
            </button>
          </li>
          <li>
            <button className="dropdown-item d-flex align-items-center gap-2" onClick={copyZekr}>
              <IconCopy size="18" />
              <span>نسخ</span>
            </button>
          </li>
          <li>
            <hr className="dropdown-divider" />
          </li>
          <li>
            <button className="dropdown-item d-flex align-items-center gap-2" disabled={count === 0} onClick={reset}>
              <IconRestore size="18" />
              <span>تصفير</span>
            </button>
          </li>
        </ul>
      </div>

      <div className="row align-items-center g-4 text-center text-lg-start">
        <div className="col-12 col-lg-auto">
          <button
            data-zekr-counter
            aria-label="عداد الذكر"
            className={`btn ${styles.counter} border-flat`}
            onClick={(event) => {
              event.stopPropagation()
              increment()
            }}
            style={{ '--progress': count / repeat }}
            data-content={toArabicNumerals(`${count}/${repeat}`)}
          ></button>
        </div>

        <div className="col-12 col-lg">
          <p className={`${styles.text} font-quran m-0`}>{text}</p>

          {(benefit || reference) && (
            <p className="text-muted m-0 pe-2">
              {reference && <small>{reference}</small>}
              {benefit && reference && <small> - </small>}
              {benefit && <small>{benefit}</small>}
            </p>
          )}
        </div>
      </div>
    </div>
  )
}
