// src/features/sebha/views/SebhaView.vue
<script setup>
import Page from '@/layout/Page.vue'
import Heading from '@/shared/ui/Heading.vue'
import Sebha from '@/features/sebha/components/Sebha.vue'
import { useMediaQuery } from '@vueuse/core'

const isMobile = useMediaQuery('(max-width: 768px)')
</script>

<template>
  <Page :class="{ 'sebha-page': true, 'full-height': isMobile }">
    <Heading
      class="mb-4"
      title="السبحة الإلكترونية"
      subtitle="السبحة الإلكترونية هي تطبيق يساعدك على ذكر الله في أي وقت ومكان."
      :share="true"
    />

    <Sebha />
  </Page>
</template>

<style lang="scss" scoped>
.sebha-page {
  display: grid;
  grid-template-rows: auto 1fr;
}
</style>

// src/features/sebha/views/SebhaView.jsx
import Page from '@/layout/Page'
import Heading from '@/shared/ui/Heading'
import Sebha from '@/features/sebha/components/Sebha'
import { useMediaQuery } from '@/shared/hooks/useMediaQuery'
import styles from './SebhaView.module.scss'

export default function SebhaView() {
  const isMobile = useMediaQuery('(max-width: 768px)')

  return (
    <Page className={`${styles.page} ${isMobile ? 'full-height' : ''}`}>
      <Heading
        className="mb-4"
        title="السبحة الإلكترونية"
        subtitle="السبحة الإلكترونية هي تطبيق يساعدك على ذكر الله في أي وقت ومكان."
        share
      />

      <Sebha />
    </Page>
  )
}
