// src/features/quran/views/QuranSurahView.vue
<script setup>
import { computed, nextTick, ref, watch } from 'vue'
import { IconArrowLeft, IconArrowRight } from '@tabler/icons-vue'
import { useOnline } from '@vueuse/core'
import { useRoute } from 'vue-router'
import { useRouteParams } from '@vueuse/router'
import { toast } from 'vue-sonner'

import Page from '@/layout/Page.vue'
import Heading from '@/shared/ui/Heading.vue'
import BackButton from '@/shared/ui/BackButton.vue'
import AsyncContent from '@/shared/ui/AsyncContent.vue'
import AudioPlayer from '@/features/quran/components/QuranPlayer.vue'
import AyahActionSheet from '@/features/quran/components/AyahActionSheet.vue'
import TafseerSheet from '@/features/quran/components/TafseerSheet.vue'
import { useQuranStore } from '@/features/quran/store'
import { useQuranBookmark } from '@/features/quran/composables/useQuranBookmark'
import { useAsyncData } from '@/shared/composables/useAsyncData'
import { usePageMeta } from '@/shared/composables/usePageMeta'
import { toArabicNumerals, removeBismillah } from '@/shared/utils/arabic'
import { fetchSurah } from '@/features/quran/api'

const online = useOnline()
const route = useRoute()
const surahId = useRouteParams('surah')
const quranStore = useQuranStore()
const { isBookmarked, toggleBookmark } = useQuranBookmark()
const playerRef = ref(null)

const {
  data: surah,
  error,
  pending: isFetching,
  execute: reloadSurah,
} = useAsyncData(async () => {
  const result = await fetchSurah(surahId.value)
  if (online.value && result) {
    await quranStore.loadSurahAudio(result.data.number, result.data.name)
  }
  return result
})

// Vue Router reuses this component when only the :surah param changes (e.g. the
// prev/next buttons), so re-fetch and scroll back to the top on each switch.
watch(surahId, () => {
  reloadSurah()
  window.scrollTo({ top: 0 })
})

const revelationLabel = computed(() => (surah.value?.data.revelationType === 'Meccan' ? 'مكية' : 'مدنية'))
const surahNumber = computed(() => Number(surahId.value))

usePageMeta(
  () =>
    surah.value && {
      title: surah.value.data.name,
      description: `قراءة وتلاوة سورة ${surah.value.data.name} - ${toArabicNumerals(surah.value.data.numberOfAyahs)} آية - سورة ${revelationLabel.value}`,
      keywords: ['قرآن', 'سورة', surah.value.data.name, 'تلاوة', 'قراءة', 'رفيق'],
    },
)

const ayat = computed(() => {
  if (surah.value) {
    let ayat = surah.value.data.ayahs

    if (surah.value.data.number === 1) {
      ayat = ayat.slice(1)
    }

    return ayat.map((ayah) => {
      const text = (ayah.numberInSurah === 1 ? removeBismillah(ayah.text) : ayah.text).trim()

      return {
        ...ayah,
        text,
      }
    })
  }

  return []
})

const activeAyah = ref(null)
const tafseerAyah = ref(null)

// Navigate the tafseer sheet through the surah's ayat without leaving the sheet.
const tafseerIndex = computed(() => ayat.value.findIndex((a) => a.number === tafseerAyah.value?.number))

const stepTafseer = (delta) => {
  const next = ayat.value[tafseerIndex.value + delta]
  if (next) tafseerAyah.value = next
}

const reciteAyah = () => {
  playerRef.value?.seekToAyah(activeAyah.value?.numberInSurah)
}

const isCurrentVerse = (verse) => {
  const currentAyah = quranStore.currentAyah
  if (!currentAyah || !surah.value) return false
  return currentAyah.ayah === verse.numberInSurah
}

const isBookmarkedVerse = (verse) => isBookmarked(surahId.value, verse.numberInSurah)

const handleBookmark = () => {
  const ayah = activeAyah.value
  if (!ayah || !surah.value) return

  const wasBookmarked = isBookmarkedVerse(ayah)
  toggleBookmark({
    surahId: surah.value.data.number,
    surahName: surah.value.data.name,
    ayahNumber: ayah.numberInSurah,
    text: ayah.text,
  })
  toast.success(wasBookmarked ? 'تمت إزالة الإشارة المرجعية' : 'تم حفظ الإشارة المرجعية')
}

const scrollToAyah = (ayahNumber) => {
  const el = document.getElementById(`ayah-${ayahNumber}`)
  el?.scrollIntoView({ behavior: 'smooth', block: 'center' })
}

// When arriving with ?ayah=N (e.g. from the bookmark card), bring that ayah
// into view once the surah has rendered.
watch(
  [surah, () => route.query.ayah],
  ([loadedSurah, ayahQuery]) => {
    if (!loadedSurah || !ayahQuery) return
    nextTick(() => scrollToAyah(Number(ayahQuery)))
  },
  { immediate: true },
)
</script>

<template>
  <AsyncContent :pending="isFetching" :error="error" loading-message="جاري تحميل السورة...">
    <Page class="quran-page" v-if="surah">
      <Heading
        :title="surah.data.name"
        :subtitle="`عدد الآيات: ${toArabicNumerals(surah.data.numberOfAyahs)} آية - سورة ${revelationLabel}`"
        :share="true"
      />

      <!-- Audio Player -->
      <AudioPlayer v-if="online" ref="playerRef" />

      <div class="ayat font-quran mb-4">
        <span class="basmallah" v-if="surahId != 9">بِسْمِ ٱللَّهِ ٱلرَّحۡمَـٰنِ ٱلرَّحِیمِ</span>

        <template v-for="(ayah, index) in ayat" :key="ayah.number">
          <span
            :id="`ayah-${ayah.numberInSurah}`"
            class="ayah clickable-ayah"
            :class="{ 'current-ayah': isCurrentVerse(ayah), 'bookmarked-ayah': isBookmarkedVerse(ayah) }"
            @click="activeAyah = ayah"
            :title="`خيارات الآية ${toArabicNumerals(ayah.numberInSurah)}`"
            >{{ ayah.text }}</span
          >
          <span class="ayah-number" aria-hidden="true">{{ toArabicNumerals(ayah.numberInSurah) }}</span>
          <div v-if="index < ayat.length - 1 && ayah.page !== ayat[index + 1].page" class="page-separator">
            <span class="page-number">{{ toArabicNumerals(ayah.page) }}</span>
          </div>
        </template>
      </div>

      <div class="d-flex justify-content-center align-items-center gap-2">
        <RouterLink
          v-if="surahNumber > 1"
          :to="{ name: 'quran-surah', params: { surah: surahNumber - 1 } }"
          class="btn btn-flat d-inline-flex align-items-center gap-2"
        >
          <IconArrowRight size="1.25rem" />
          <span>السابقة</span>
        </RouterLink>

        <BackButton :to="{ name: 'quran' }" button-class="btn-primary" />

        <RouterLink
          v-if="surahNumber < 114"
          :to="{ name: 'quran-surah', params: { surah: surahNumber + 1 } }"
          class="btn btn-flat d-inline-flex align-items-center gap-2"
        >
          <span>التالية</span>
          <IconArrowLeft size="1.25rem" />
        </RouterLink>
      </div>

      <AyahActionSheet
        :ayah="activeAyah"
        :surah-name="surah.data.name"
        :online="online"
        :bookmarked="!!activeAyah && isBookmarkedVerse(activeAyah)"
        @recite="reciteAyah"
        @tafseer="tafseerAyah = activeAyah"
        @bookmark="handleBookmark"
        @close="activeAyah = null"
      />

      <TafseerSheet
        :ayah="tafseerAyah"
        :has-prev="tafseerIndex > 0"
        :has-next="tafseerIndex >= 0 && tafseerIndex < ayat.length - 1"
        @prev="stepTafseer(-1)"
        @next="stepTafseer(1)"
        @close="tafseerAyah = null"
      />
    </Page>
  </AsyncContent>
</template>

<style lang="scss" scoped>
@import '@/shared/styles/quran.css';

.quran-page {
  display: flex;
  flex-direction: column;
  gap: 10px;
  max-width: 700px;

  .ayat {
    padding: 1rem;
    border-radius: 5px;
    border: 1px solid var(--bs-border-color);
    text-align: justify;
    text-align-last: center;
    text-justify: inter-word;

    .basmallah {
      display: block;
      font-size: 2rem;
      line-height: 2.5;
      text-align: center;
      margin-bottom: 1rem;
    }

    .ayah {
      line-height: 2;
      font-size: 1.625rem;
    }

    .ayah,
    .ayah-number {
      margin-bottom: 0.75rem;
    }

    .page-separator {
      display: flex;
      align-items: center;
      width: 100%;
      margin: 2rem 0;

      &::before,
      &::after {
        content: '';
        flex: 1;
        border-bottom: 1px solid var(--bs-border-color);
      }

      .page-number {
        padding: 0.15rem 0.75rem;
        font-size: 0.875rem;
        color: var(--bs-gray-600);
        font-family: 'IBM Plex Sans Arabic', sans-serif;
        white-space: nowrap;
        border: 1px solid var(--bs-border-color);
        border-radius: 999px;
      }
    }

    .clickable-ayah {
      cursor: pointer;
    }

    .current-ayah {
      background-color: var(--bs-secondary-bg);
    }

    .bookmarked-ayah {
      background-color: rgba(var(--bs-primary-rgb), 0.12);
      box-shadow: 0 0 0 1px rgba(var(--bs-primary-rgb), 0.35);
      border-radius: 6px;
      padding: 0 0.25rem;
    }
  }
}
</style>

// src/features/quran/views/QuranSurahView.jsx
import { Fragment, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { IconArrowLeft, IconArrowRight } from '@tabler/icons-react'
import { toast } from 'sonner'

import Page from '@/layout/Page'
import Heading from '@/shared/ui/Heading'
import BackButton from '@/shared/ui/BackButton'
import AsyncContent from '@/shared/ui/AsyncContent'
import QuranPlayer from '@/features/quran/components/QuranPlayer'
import AyahActionSheet from '@/features/quran/components/AyahActionSheet'
import TafseerSheet from '@/features/quran/components/TafseerSheet'
import { fetchSurah } from '@/features/quran/api'
import { useQuranStore, selectCurrentAyah } from '@/features/quran/store'
import { useQuranBookmark } from '@/features/quran/hooks/useQuranBookmark'
import { useAsyncData } from '@/shared/hooks/useAsyncData'
import { useOnline } from '@/shared/hooks/useOnline'
import { usePageMeta } from '@/shared/hooks/usePageMeta'
import { ROUTES } from '@/app/router/routes'
import { toArabicNumerals, removeBismillah, normalizeQuranicText } from '@/shared/utils/arabic'
import styles from './QuranSurahView.module.scss'

const FIRST_SURAH = 1
const LAST_SURAH = 114

export default function QuranSurahView() {
  const { surah: surahParam } = useParams()
  const [searchParams] = useSearchParams()
  const surahNumber = Number(surahParam)

  const online = useOnline()
  const playerRef = useRef(null)

  const { isBookmarked, toggleBookmark } = useQuranBookmark()
  const currentAyah = useQuranStore(selectCurrentAyah)

  const fetcher = useCallback(async () => {
    const result = await fetchSurah(surahParam)

    if (navigator.onLine && result) {
      await useQuranStore.getState().loadSurahAudio(result.data.number, result.data.name)
    }

    return result
  }, [surahParam])

  const { data: surah, error, pending: isFetching } = useAsyncData(fetcher, { deps: [surahParam] })

  // The component is reused when only the :surah param changes (e.g. the
  // prev/next buttons), so scroll back to the top on each switch.
  useEffect(() => {
    window.scrollTo({ top: 0 })
  }, [surahParam])

  const revelationLabel = surah?.data.revelationType === 'Meccan' ? 'مكية' : 'مدنية'

  usePageMeta(
    surah && {
      title: surah.data.name,
      description: `قراءة وتلاوة سورة ${surah.data.name} - ${toArabicNumerals(surah.data.numberOfAyahs)} آية - سورة ${revelationLabel}`,
      keywords: ['قرآن', 'سورة', surah.data.name, 'تلاوة', 'قراءة', 'رفيق'],
    },
  )

  const ayat = useMemo(() => {
    if (!surah) return []

    // Al-Fatiha counts the basmala as its first ayah; every other surah carries
    // it as a prefix of the first ayah's text.
    const verses = surah.data.number === 1 ? surah.data.ayahs.slice(1) : surah.data.ayahs

    return verses.map((ayah) => ({
      ...ayah,
      text: (ayah.numberInSurah === 1 ? removeBismillah(ayah.text) : ayah.text).trim(),
    }))
  }, [surah])

  // Each sheet keeps its ayah after closing, so its content doesn't vanish
  // mid-animation; `show` alone drives open/closed.
  const [activeAyah, setActiveAyah] = useState(null)
  const [showActions, setShowActions] = useState(false)
  const [tafseerAyah, setTafseerAyah] = useState(null)
  const [showTafseer, setShowTafseer] = useState(false)

  // Navigate the tafseer sheet through the surah's ayat without leaving the sheet.
  const tafseerIndex = ayat.findIndex((ayah) => ayah.number === tafseerAyah?.number)
  const stepTafseer = (delta) => {
    const next = ayat[tafseerIndex + delta]
    if (next) setTafseerAyah(next)
  }

  const openActions = (ayah) => {
    setActiveAyah(ayah)
    setShowActions(true)
  }

  const openTafseer = () => {
    setTafseerAyah(activeAyah)
    setShowTafseer(true)
  }

  const isBookmarkedVerse = (verse) => isBookmarked(surahParam, verse.numberInSurah)

  const handleBookmark = () => {
    if (!activeAyah || !surah) return

    const wasBookmarked = isBookmarkedVerse(activeAyah)

    toggleBookmark({
      surahId: surah.data.number,
      surahName: surah.data.name,
      ayahNumber: activeAyah.numberInSurah,
      text: activeAyah.text,
    })

    toast.success(wasBookmarked ? 'تمت إزالة الإشارة المرجعية' : 'تم حفظ الإشارة المرجعية')
  }

  // When arriving with ?ayah=N (e.g. from the bookmark card), bring that ayah
  // into view once the surah has rendered.
  const requestedAyah = searchParams.get('ayah')
  useEffect(() => {
    if (!surah || !requestedAyah) return

    document.getElementById(`ayah-${Number(requestedAyah)}`)?.scrollIntoView({ behavior: 'smooth', block: 'center' })
  }, [surah, requestedAyah])

  return (
    <AsyncContent pending={isFetching} error={error} loadingMessage="جاري تحميل السورة...">
      {surah && (
        <Page className={styles.page}>
          <Heading
            title={normalizeQuranicText(surah.data.name)}
            subtitle={`عدد الآيات: ${toArabicNumerals(surah.data.numberOfAyahs)} آية - سورة ${revelationLabel}`}
            share
          />

          {online && <QuranPlayer ref={playerRef} />}

          <div className={`${styles.ayat} font-quran mb-4`}>
            {surahNumber !== 9 && <span className={styles.basmallah}>بِسْمِ ٱللَّهِ ٱلرَّحۡمَـٰنِ ٱلرَّحِیمِ</span>}

            {ayat.map((ayah, index) => (
              <Fragment key={ayah.number}>
                <span
                  id={`ayah-${ayah.numberInSurah}`}
                  className={`ayah ${currentAyah?.ayah === ayah.numberInSurah ? styles.currentAyah : ''} ${
                    isBookmarkedVerse(ayah) ? styles.bookmarkedAyah : ''
                  }`}
                  onClick={() => openActions(ayah)}
                  title={`خيارات الآية ${toArabicNumerals(ayah.numberInSurah)}`}
                >
                  {ayah.text}
                </span>
                <span className="ayah-number" aria-hidden="true">
                  {toArabicNumerals(ayah.numberInSurah)}
                </span>
                {index < ayat.length - 1 && ayah.page !== ayat[index + 1].page && (
                  <div className={styles.pageSeparator}>
                    <span className={styles.pageNumber}>{toArabicNumerals(ayah.page)}</span>
                  </div>
                )}
              </Fragment>
            ))}
          </div>

          <div className="d-flex justify-content-center align-items-center gap-2">
            <Link
              to={ROUTES.quranSurah(surahNumber - 1)}
              className={`btn btn-flat d-inline-flex align-items-center gap-2 ${surahNumber === FIRST_SURAH ? 'disabled' : ''}`}
            >
              <IconArrowRight size="1.25rem" />
              <span>السابقة</span>
            </Link>

            <BackButton to={ROUTES.quran} buttonClass="btn-primary" />

            <Link
              to={ROUTES.quranSurah(surahNumber + 1)}
              className={`btn btn-flat d-inline-flex align-items-center gap-2 ${surahNumber === LAST_SURAH ? 'disabled' : ''}`}
            >
              <span>التالية</span>
              <IconArrowLeft size="1.25rem" />
            </Link>
          </div>

          <AyahActionSheet
            show={showActions}
            ayah={activeAyah}
            surahName={surah.data.name}
            online={online}
            bookmarked={!!activeAyah && isBookmarkedVerse(activeAyah)}
            onRecite={() => playerRef.current?.seekToAyah(activeAyah?.numberInSurah)}
            onTafseer={openTafseer}
            onBookmark={handleBookmark}
            onClose={() => setShowActions(false)}
          />

          <TafseerSheet
            show={showTafseer}
            ayah={tafseerAyah}
            hasPrev={tafseerIndex > 0}
            hasNext={tafseerIndex >= 0 && tafseerIndex < ayat.length - 1}
            onPrev={() => stepTafseer(-1)}
            onNext={() => stepTafseer(1)}
            onClose={() => setShowTafseer(false)}
          />
        </Page>
      )}
    </AsyncContent>
  )
}
