// src/features/settings/components/SettingsPrayerTimes.jsx
import {
  IconRefreshDot,
  IconTrash,
  IconLayoutList,
  IconLayoutGrid,
  IconDevices,
  IconClockHour4,
} from '@tabler/icons-react'

import SettingsSection from './SettingsSection'
import { usePrayersStore, selectHasLocation } from '@/features/prayers/store'
import { usePrayerLocation } from '@/features/prayers/hooks/usePrayerLocation'
import { CALCULATION_FIELDS } from '@/features/prayers/constants/calculationOptions'

const LAYOUTS = [
  { value: 'cards', label: 'بطاقات', icon: IconLayoutGrid },
  { value: 'list', label: 'قائمة', icon: IconLayoutList },
  { value: 'auto', label: 'تلقائي', icon: IconDevices },
]

export default function SettingsPrayerTimes() {
  const store = usePrayersStore()
  const { detect } = usePrayerLocation()

  const location = selectHasLocation(store) ? `${store.latitude}, ${store.longitude}` : 'لم يتم تحديد الموقع'

  return (
    <SettingsSection title="مواقيت الصلاة" description="حدّد موقعك وطريقة عرض المواقيت" icon={IconClockHour4}>
      <div className="mb-3">
        <span className="d-block mb-2">طريقة العرض</span>
        <div className="btn-group-toggle">
          {LAYOUTS.map((layout) => (
            <button
              key={layout.value}
              className={`btn-toggle ${store.layout === layout.value ? 'active' : ''}`}
              onClick={() => store.setLayout(layout.value)}
            >
              <layout.icon size={16} />
              <span>{layout.label}</span>
            </button>
          ))}
        </div>
      </div>

      <div className="mb-3">
        <div className="input-group">
          <div className="form-floating">
            <input id="location" type="text" className="form-control" value={location} readOnly />
            <label htmlFor="location">الموقع</label>
          </div>

          <button type="button" className="input-group-text" onClick={detect} aria-label="تحديد الموقع">
            <IconRefreshDot size="1.25rem" />
          </button>

          <button type="button" className="input-group-text" onClick={store.clear} aria-label="مسح الموقع">
            <IconTrash size="1.25rem" />
          </button>
        </div>
      </div>

      {CALCULATION_FIELDS.map((field) => (
        <div key={field.key} className="mb-3">
          <div className="form-floating">
            <select
              id={field.key}
              className="form-select"
              value={store[field.key]}
              onChange={(event) => store.setCalculationField(field.key, event.target.value)}
            >
              {field.options.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label}
                </option>
              ))}
            </select>
            <label htmlFor={field.key}>{field.label}</label>
          </div>
        </div>
      ))}
    </SettingsSection>
  )
}

// src/views/settings/partials/SettingsPrayerTimes.vue
<script setup>
import { computed } from 'vue'
import { usePrayersStore } from '@/stores/prayers'
import {
  IconRefreshDot,
  IconTrash,
  IconLayoutList,
  IconLayoutGrid,
  IconDevices,
  IconClockHour4,
} from '@tabler/icons-vue'
import SettingsSection from './SettingsSection.vue'

const store = usePrayersStore()

const location = computed(() => {
  if (store.latitude === 0 || store.longitude === 0) {
    return 'لم يتم تحديد الموقع'
  }

  return `${store.latitude}, ${store.longitude}`
})
</script>

<template>
  <SettingsSection title="مواقيت الصلاة" description="حدّد موقعك وطريقة عرض المواقيت" :icon="IconClockHour4">
    <div class="mb-3">
      <span class="d-block mb-2">الموقع</span>
      <div class="input-group">
        <div class="form-floating">
          <input type="text" class="form-control" id="location" :value="location" readonly />
          <label for="location">الموقع</label>
        </div>

        <button type="button" class="input-group-text" @click="store.detect">
          <IconRefreshDot size="1.25rem" />
        </button>

        <button type="button" class="input-group-text" @click="store.clear">
          <IconTrash size="1.25rem" />
        </button>
      </div>
    </div>

    <div>
      <span class="d-block mb-2">طريقة العرض</span>
      <div class="btn-group-toggle">
        <button class="btn-toggle" :class="{ active: store.layout === 'cards' }" @click="store.layout = 'cards'">
          <IconLayoutGrid :size="16" />
          <span>بطاقات</span>
        </button>
        <button class="btn-toggle" :class="{ active: store.layout === 'list' }" @click="store.layout = 'list'">
          <IconLayoutList :size="16" />
          <span>قائمة</span>
        </button>
        <button class="btn-toggle" :class="{ active: store.layout === 'auto' }" @click="store.layout = 'auto'">
          <IconDevices :size="16" />
          <span>تلقائي</span>
        </button>
      </div>
    </div>
  </SettingsSection>
</template>
