// src/features/quran/components/RandomAyah.jsx
import { useEffect, useMemo, useRef, useState } from 'react'
import { IconRefresh, IconChevronRight, IconChevronLeft, IconPlayerPlay, IconPlayerPause } from '@tabler/icons-react'
import { toast } from 'sonner'

import LoadingState from '@/shared/ui/LoadingState'
import ErrorState from '@/shared/ui/ErrorState'
import OfflineState from '@/shared/ui/OfflineState'
import { useQuranStore } from '@/features/quran/store'
import { useJsonFetch } from '@/shared/hooks/useJsonFetch'
import { useOnline } from '@/shared/hooks/useOnline'
import { useReconnectExecute } from '@/shared/hooks/useReconnectExecute'
import { toArabicNumerals, removeBismillah, normalizeQuranicText } from '@/shared/utils/arabic'
import { API } from '@/shared/constants/api'

const TOTAL_AYAHS = 6236

const randomAyahNumber = () => Math.floor(Math.random() * TOTAL_AYAHS) + 1

export default function RandomAyah({ className = '' }) {
  const online = useOnline()
  const currentTafseer = useQuranStore((state) => state.currentTafseer)

  const [current, setCurrent] = useState(randomAyahNumber)

  const endpoint = `${API.quranCloud}/ayah/${current}/editions/${['quran-uthmani', currentTafseer, 'ar.alafasy'].join(',')}`
  const { data, error, pending: isFetching, execute } = useJsonFetch(endpoint)
  const { isRecoveringOnReconnect } = useReconnectExecute(execute)

  const [ayah, tafsir, recitation] = data?.data ?? []

  const audioRef = useRef(null)
  if (audioRef.current === null) audioRef.current = new Audio()

  const [isPlaying, setIsPlaying] = useState(false)

  useEffect(() => {
    const audio = audioRef.current

    const onPlay = () => setIsPlaying(true)
    const onStop = () => setIsPlaying(false)

    audio.addEventListener('play', onPlay)
    audio.addEventListener('pause', onStop)
    audio.addEventListener('ended', onStop)

    return () => {
      audio.pause()
      audio.currentTime = 0
      audio.removeEventListener('play', onPlay)
      audio.removeEventListener('pause', onStop)
      audio.removeEventListener('ended', onStop)
    }
  }, [])

  // Switching ayah stops whatever is playing and arms the new recitation.
  useEffect(() => {
    const audio = audioRef.current
    audio.pause()
    audio.currentTime = 0
    if (recitation?.audio) audio.src = recitation.audio
  }, [recitation?.audio])

  const displayText = useMemo(() => {
    if (!ayah?.text) return ''
    if (ayah.surah.number !== 1 && ayah.numberInSurah === 1) return removeBismillah(ayah.text)
    return ayah.text.trim()
  }, [ayah])

  const toggleAyahPlayback = async () => {
    if (!recitation?.audio) return

    if (isPlaying) {
      audioRef.current.pause()
      return
    }

    try {
      await audioRef.current.play()
    } catch {
      toast.error('تعذر تشغيل التلاوة، برجاء المحاولة مرة أخرى')
    }
  }

  const step = (delta) => setCurrent((value) => ((value - 1 + delta + TOTAL_AYAHS) % TOTAL_AYAHS) + 1)

  return (
    <div className={`card ${className}`}>
      {isFetching || isRecoveringOnReconnect ? (
        <div className="card-body p-5">
          <LoadingState message="جاري تحميل آية..." />
        </div>
      ) : error ? (
        <div className="card-body p-5">
          {online ? (
            <ErrorState code={500} message="حدث خطأ أثناء تحميل الآية، برجاء المحاولة مرة أخرى." />
          ) : (
            <OfflineState />
          )}
        </div>
      ) : (
        ayah && (
          <>
            <div className="card-header d-flex align-items-center justify-content-between py-2">
              <span className="fw-semibold">{normalizeQuranicText(ayah.surah.name)}</span>

              <div className="d-flex align-items-center gap-1">
                <button
                  className="btn btn-flat btn-icon"
                  onClick={() => step(-1)}
                  title="الآية السابقة"
                  aria-label="الآية السابقة"
                >
                  <IconChevronRight size="18" />
                </button>

                <button
                  className="btn btn-flat btn-icon"
                  onClick={() => step(1)}
                  title="الآية التالية"
                  aria-label="الآية التالية"
                >
                  <IconChevronLeft size="18" />
                </button>

                <button
                  className="btn btn-flat btn-icon"
                  onClick={toggleAyahPlayback}
                  disabled={!recitation?.audio}
                  title={isPlaying ? 'إيقاف التلاوة' : 'تشغيل التلاوة'}
                  aria-label={isPlaying ? 'إيقاف التلاوة' : 'تشغيل التلاوة'}
                >
                  {isPlaying ? <IconPlayerPause size="18" /> : <IconPlayerPlay size="18" />}
                </button>

                <button
                  className="btn btn-flat btn-icon"
                  onClick={() => setCurrent(randomAyahNumber)}
                  title="آية جديدة"
                  aria-label="تحميل آية جديدة"
                >
                  <IconRefresh size="18" />
                </button>
              </div>
            </div>

            <div className="card-body">
              <p className={`fs-2 text-center lh-lg font-quran ${tafsir ? 'mb-4' : 'mb-0'}`}>
                {displayText} <span className="ayah-number">{toArabicNumerals(ayah.numberInSurah)}</span>
              </p>

              {tafsir && (
                <>
                  <span className="d-block small fw-semibold text-secondary mb-2">{tafsir.edition.name}</span>
                  <p className="small mb-0">{tafsir.text}</p>
                </>
              )}
            </div>
          </>
        )
      )}
    </div>
  )
}

// src/features/quran/RandomAyah.vue
<script setup>
import { computed, ref, watch, onUnmounted } from 'vue'
import { useFetch, useOnline } from '@vueuse/core'
import { toast } from 'vue-sonner'
import { toArabicNumerals, removeBismillah } from '@/shared/utils/arabic'
import { IconRefresh, IconChevronRight, IconChevronLeft, IconPlayerPlay, IconPlayerPause } from '@tabler/icons-vue'
import { useReconnectExecute } from '@/shared/composables/useReconnectExecute'

import LoadingState from '@/shared/ui/LoadingState.vue'
import ErrorState from '@/shared/ui/ErrorState.vue'
import OfflineState from '@/shared/ui/OfflineState.vue'

// Check if the user is online
const online = useOnline()

const TOTAL_AYAHS = 6236
const current = ref(Math.floor(Math.random() * TOTAL_AYAHS) + 1)
const editions = ['quran-uthmani', 'ar.muyassar', 'ar.alafasy']
const endpoint = computed(() => `https://api.alquran.cloud/v1/ayah/${current.value}/editions/${editions.join(',')}`)

const { isFetching, data, error, execute } = useFetch(endpoint, { refetch: true }).json().get()
const ayah = computed(() => data.value?.data?.[0])
const tafsir = computed(() => data.value?.data?.[1])
const recitation = computed(() => data.value?.data?.[2])
const { isRecoveringOnReconnect } = useReconnectExecute(online, execute)

const audio = new Audio()
const isPlaying = ref(false)

watch(current, () => {
  audio.pause()
  audio.currentTime = 0
  isPlaying.value = false
})

watch(recitation, (value) => {
  if (value?.audio) audio.src = value.audio
})

audio.addEventListener('play', () => {
  isPlaying.value = true
})

audio.addEventListener('pause', () => {
  isPlaying.value = false
})

audio.addEventListener('ended', () => {
  isPlaying.value = false
})

onUnmounted(() => {
  audio.pause()
  audio.currentTime = 0
})

const displayText = computed(() => {
  if (!ayah.value?.text) return ''

  if (ayah.value.surah.number !== 1 && ayah.value.numberInSurah === 1) {
    return removeBismillah(ayah.value.text)
  }

  return ayah.value.text.trim()
})

function fetchRandomAyah() {
  current.value = Math.floor(Math.random() * TOTAL_AYAHS) + 1
}

function nextAyah() {
  current.value = current.value >= TOTAL_AYAHS ? 1 : current.value + 1
}

function prevAyah() {
  current.value = current.value <= 1 ? TOTAL_AYAHS : current.value - 1
}

async function toggleAyahPlayback() {
  if (!recitation.value?.audio) return

  if (isPlaying.value) {
    audio.pause()
    return
  }

  try {
    await audio.play()
  } catch {
    toast.error('تعذر تشغيل التلاوة، برجاء المحاولة مرة أخرى')
  }
}
</script>

<template>
  <div class="card">
    <div v-if="isFetching || isRecoveringOnReconnect" class="card-body p-5">
      <LoadingState message="جاري تحميل آية..." />
    </div>

    <div v-else-if="error" class="card-body p-5">
      <OfflineState v-if="!online" />
      <ErrorState :code="500" message="حدث خطأ أثناء تحميل الآية، برجاء المحاولة مرة أخرى." v-else />
    </div>

    <template v-else-if="ayah && tafsir">
      <div class="card-header d-flex align-items-center justify-content-between py-3">
        <span class="fw-semibold">{{ ayah.surah.name }}</span>

        <div class="d-flex align-items-center gap-1">
          <button class="btn btn-flat" @click="prevAyah" title="الآية السابقة" aria-label="الآية السابقة">
            <IconChevronRight size="18" />
          </button>

          <button class="btn btn-flat" @click="nextAyah" title="الآية التالية" aria-label="الآية التالية">
            <IconChevronLeft size="18" />
          </button>

          <button
            class="btn btn-flat"
            @click="toggleAyahPlayback"
            :disabled="!recitation?.audio"
            :title="isPlaying ? 'إيقاف التلاوة' : 'تشغيل التلاوة'"
            :aria-label="isPlaying ? 'إيقاف التلاوة' : 'تشغيل التلاوة'"
          >
            <IconPlayerPause v-if="isPlaying" size="18" />
            <IconPlayerPlay v-else size="18" />
          </button>

          <button class="btn btn-flat" @click="fetchRandomAyah" title="آية جديدة" aria-label="تحميل آية جديدة">
            <IconRefresh size="18" />
          </button>
        </div>
      </div>

      <div class="card-body">
        <p class="fs-2 text-center lh-lg font-quran mb-4">
          {{ displayText }} <span class="ayah-number">{{ toArabicNumerals(ayah.numberInSurah) }}</span>
        </p>

        <span class="d-block small fw-semibold text-secondary mb-2">{{ tafsir.edition.name }}</span>
        <p class="small mb-0">{{ tafsir.text }}</p>
      </div>
    </template>
  </div>
</template>

<style lang="scss" scoped>
@import '@/shared/styles/quran.css';
</style>
