// src/features/azkar/views/AzkarCategoryView.jsx
import { useCallback, useMemo } from 'react'
import { useBlocker, useParams } from 'react-router-dom'
import { IconDoorExit, IconArrowBackUp, IconRestore } from '@tabler/icons-react'

import Page from '@/layout/Page'
import Heading from '@/shared/ui/Heading'
import BackButton from '@/shared/ui/BackButton'
import AsyncContent from '@/shared/ui/AsyncContent'
import BottomSheet from '@/shared/ui/BottomSheet'
import ZekrCard from '@/features/azkar/components/ZekrCard'
import { fetchCategory } from '@/features/azkar/api'
import { useAzkarProgress } from '@/features/azkar/hooks/useAzkarProgress'
import { useAppStore } from '@/app/stores/app'
import { useAsyncData } from '@/shared/hooks/useAsyncData'
import { usePageMeta } from '@/shared/hooks/usePageMeta'
import { ROUTES } from '@/app/router/routes'

export default function AzkarCategoryView() {
  const { category: slug } = useParams()

  const saveProgress = useAppStore((state) => state.zekrSaveProgress)
  const confirmOnLeave = useAppStore((state) => state.zekrConfirmOnLeave)

  const { counts, setCount, reset: resetProgress } = useAzkarProgress(slug, saveProgress)

  const fetcher = useCallback(() => fetchCategory(slug), [slug])
  const { data: category, error, pending: isFetching } = useAsyncData(fetcher, { deps: [slug] })

  usePageMeta(
    category && {
      title: category.meta.name,
      description: category.meta.description,
      keywords: ['أذكار', 'دعاء', category.meta.name, 'رفيق'],
    },
  )

  // Track progress across all azkar, derived from the persisted per-zekr counts.
  const azkar = useMemo(() => category?.content ?? [], [category])
  const totalRepeats = useMemo(() => azkar.reduce((sum, zekr) => sum + (zekr.repeat || 1), 0), [azkar])
  const totalClicked = useMemo(() => azkar.reduce((sum, _, index) => sum + (counts[index] || 0), 0), [azkar, counts])

  const progress = totalRepeats > 0 ? (totalClicked / totalRepeats) * 100 : 0
  const hasUnfinishedProgress = progress > 0 && progress < 100

  const blocker = useBlocker(
    useCallback(
      ({ currentLocation, nextLocation }) =>
        confirmOnLeave && hasUnfinishedProgress && currentLocation.pathname !== nextLocation.pathname,
      [confirmOnLeave, hasUnfinishedProgress],
    ),
  )

  return (
    <>
      <AsyncContent pending={isFetching} error={error} loadingMessage="جاري تحميل الأذكار...">
        {category && (
          <Page>
            <Heading className="mb-4" title={category.meta.name} subtitle={category.meta.description} share />

            {azkar.map((zekr, index) => (
              <ZekrCard
                key={index}
                className="mb-3"
                count={counts[index] ?? 0}
                onCountChange={(count) => setCount(index, count)}
                text={zekr.text}
                repeat={zekr.repeat}
                reference={zekr.reference}
                benefit={zekr.benefit}
              />
            ))}

            <div className="d-flex justify-content-center gap-2">
              {totalClicked > 0 && (
                <button
                  type="button"
                  className="btn btn-flat d-inline-flex align-items-center gap-2"
                  onClick={resetProgress}
                >
                  <IconRestore size="1.25rem" />
                  <span>تصفير</span>
                </button>
              )}

              <BackButton to={ROUTES.azkar} buttonClass="btn-primary" />
            </div>
          </Page>
        )}
      </AsyncContent>

      {/* Leave confirmation sheet */}
      <BottomSheet show={blocker.state === 'blocked'} title="لم تنتهِ بعد" onClose={() => blocker.reset?.()}>
        <p className="px-4 pt-3 mb-2 lh-lg text-secondary">لم تنتهِ من جميع الأذكار بعد، هل تريد المغادرة؟</p>
        <ul className="list-unstyled m-0 py-2">
          <li>
            <button className="bottom-sheet-item" onClick={() => blocker.reset?.()}>
              <IconArrowBackUp size="20" />
              <span>البقاء ومتابعة الأذكار</span>
            </button>
          </li>
          <li>
            <button className="bottom-sheet-item text-danger" onClick={() => blocker.proceed?.()}>
              <IconDoorExit size="20" />
              <span>مغادرة</span>
            </button>
          </li>
        </ul>
      </BottomSheet>
    </>
  )
}

// src/views/AzkarCategoryView.vue
<script setup>
import { ref, computed, watch } from 'vue'
import { onBeforeRouteLeave } from 'vue-router'
import { useConfirmDialog, useOnline } from '@vueuse/core'
import { useRouteParams } from '@vueuse/router'

import Page from '@/components/Layout/Page.vue'
import Heading from '@/components/Heading.vue'
import BackButton from '@/components/BackButton.vue'
import LoadingState from '@/components/LoadingState.vue'
import ErrorState from '@/components/ErrorState.vue'
import OfflineState from '@/components/OfflineState.vue'
import ZekrCard from '@/components/ZekrCard.vue'
import { useMeta } from '@/utilities/head'
import { useAzkarService } from '@/services/azkarService'

const slug = useRouteParams('category')
const online = useOnline()
const { fetchCategory } = useAzkarService()

const category = ref(null)
const isFetching = ref(true)
const error = ref(null)

async function loadCategory() {
  isFetching.value = true
  error.value = null

  try {
    category.value = await fetchCategory(slug.value)
  } catch (e) {
    error.value = e
  } finally {
    isFetching.value = false
  }
}

loadCategory()

watch(category, (val) => {
  if (val) {
    useMeta({
      title: val.meta.name,
      description: val.meta.description,
      keywords: ['أذكار', 'دعاء', val.meta.name, 'رفيق'],
    })
  }
})

// Track progress across all azkar
const totalClicked = ref(0)
const totalRepeats = computed(() => category.value?.content?.reduce((sum, z) => sum + (z.repeat || 1), 0) || 0)
const progress = computed(() => (totalRepeats.value > 0 ? (totalClicked.value / totalRepeats.value) * 100 : 0))

const hasUnfinishedProgress = () => progress.value > 0 && progress.value < 100

// Confirm dialog before leaving
const { isRevealed, reveal, confirm, cancel } = useConfirmDialog()

onBeforeRouteLeave(async () => {
  if (!hasUnfinishedProgress()) return true

  const { isCanceled } = await reveal()
  return !isCanceled
})
</script>

<template>
  <Page v-if="isFetching">
    <LoadingState message="جاري تحميل الأذكار..." />
  </Page>

  <Page v-else-if="error">
    <OfflineState v-if="!online" />
    <ErrorState :code="500" message="حدث خطأ أثناء تحميل البيانات، برجاء المحاولة في وقت لاحق." v-else />
  </Page>

  <Page v-else-if="category">
    <Heading class="mb-4" :title="category.meta.name" :subtitle="category.meta.description" :share="true" />

    <ZekrCard
      class="mb-3"
      v-for="(zekr, index) in category.content"
      :key="index"
      :text="zekr.text"
      :repeat="zekr.repeat"
      :reference="zekr.reference"
      :benefit="zekr.benefit"
      @increment="totalClicked++"
      @reset="totalClicked -= $event"
    />

    <div class="d-flex justify-content-center">
      <BackButton :to="{ name: 'azkar' }" button-class="btn-primary" />
    </div>
  </Page>

  <!-- Leave confirmation dialog -->
  <Teleport to="body">
    <div v-if="isRevealed" class="modal-backdrop show"></div>
    <div v-if="isRevealed" class="modal d-block" tabindex="-1" @click.self="cancel">
      <div class="modal-dialog modal-dialog-centered modal-md">
        <div class="modal-content text-center">
          <div class="modal-body p-4">
            <p class="mb-4 fs-5 lh-lg">لم تنتهِ من جميع الأذكار بعد، هل تريد المغادرة؟</p>
            <div class="d-flex justify-content-center gap-2">
              <button class="btn btn-primary" @click="cancel">البقاء</button>
              <button class="btn btn-danger" @click="confirm">مغادرة</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </Teleport>
</template>
