// src/features/quran/views/QuranSurahView.jsx
import { Fragment, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { IconArrowLeft, IconArrowRight } from '@tabler/icons-react'
import { toast } from 'sonner'

import Page from '@/layout/Page'
import Heading from '@/shared/ui/Heading'
import BackButton from '@/shared/ui/BackButton'
import AsyncContent from '@/shared/ui/AsyncContent'
import QuranPlayer from '@/features/quran/components/QuranPlayer'
import AyahActionSheet from '@/features/quran/components/AyahActionSheet'
import TafseerSheet from '@/features/quran/components/TafseerSheet'
import { fetchSurah } from '@/features/quran/api'
import { useQuranStore, selectCurrentAyah } from '@/features/quran/store'
import { useQuranBookmark } from '@/features/quran/hooks/useQuranBookmark'
import { useAsyncData } from '@/shared/hooks/useAsyncData'
import { useOnline } from '@/shared/hooks/useOnline'
import { usePageMeta } from '@/shared/hooks/usePageMeta'
import { ROUTES } from '@/app/router/routes'
import { toArabicNumerals, removeBismillah, normalizeQuranicText } from '@/shared/utils/arabic'
import styles from './QuranSurahView.module.scss'

const FIRST_SURAH = 1
const LAST_SURAH = 114

export default function QuranSurahView() {
  const { surah: surahParam } = useParams()
  const [searchParams] = useSearchParams()
  const surahNumber = Number(surahParam)

  const online = useOnline()
  const playerRef = useRef(null)

  const { isBookmarked, toggleBookmark } = useQuranBookmark()
  const currentAyah = useQuranStore(selectCurrentAyah)

  const fetcher = useCallback(async () => {
    const result = await fetchSurah(surahParam)

    if (navigator.onLine && result) {
      await useQuranStore.getState().loadSurahAudio(result.data.number, result.data.name)
    }

    return result
  }, [surahParam])

  const { data: surah, error, pending: isFetching } = useAsyncData(fetcher, { deps: [surahParam] })

  // The component is reused when only the :surah param changes (e.g. the
  // prev/next buttons), so scroll back to the top on each switch.
  useEffect(() => {
    window.scrollTo({ top: 0 })
  }, [surahParam])

  const revelationLabel = surah?.data.revelationType === 'Meccan' ? 'مكية' : 'مدنية'

  usePageMeta(
    surah && {
      title: surah.data.name,
      description: `قراءة وتلاوة سورة ${surah.data.name} - ${toArabicNumerals(surah.data.numberOfAyahs)} آية - سورة ${revelationLabel}`,
      keywords: ['قرآن', 'سورة', surah.data.name, 'تلاوة', 'قراءة', 'رفيق'],
    },
  )

  const ayat = useMemo(() => {
    if (!surah) return []

    // Al-Fatiha counts the basmala as its first ayah; every other surah carries
    // it as a prefix of the first ayah's text.
    const verses = surah.data.number === 1 ? surah.data.ayahs.slice(1) : surah.data.ayahs

    return verses.map((ayah) => ({
      ...ayah,
      text: (ayah.numberInSurah === 1 ? removeBismillah(ayah.text) : ayah.text).trim(),
    }))
  }, [surah])

  // Each sheet keeps its ayah after closing, so its content doesn't vanish
  // mid-animation; `show` alone drives open/closed.
  const [activeAyah, setActiveAyah] = useState(null)
  const [showActions, setShowActions] = useState(false)
  const [tafseerAyah, setTafseerAyah] = useState(null)
  const [showTafseer, setShowTafseer] = useState(false)

  // Navigate the tafseer sheet through the surah's ayat without leaving the sheet.
  const tafseerIndex = ayat.findIndex((ayah) => ayah.number === tafseerAyah?.number)
  const stepTafseer = (delta) => {
    const next = ayat[tafseerIndex + delta]
    if (next) setTafseerAyah(next)
  }

  const openActions = (ayah) => {
    setActiveAyah(ayah)
    setShowActions(true)
  }

  const openTafseer = () => {
    setTafseerAyah(activeAyah)
    setShowTafseer(true)
  }

  const isBookmarkedVerse = (verse) => isBookmarked(surahParam, verse.numberInSurah)

  const handleBookmark = () => {
    if (!activeAyah || !surah) return

    const wasBookmarked = isBookmarkedVerse(activeAyah)

    toggleBookmark({
      surahId: surah.data.number,
      surahName: surah.data.name,
      ayahNumber: activeAyah.numberInSurah,
      text: activeAyah.text,
    })

    toast.success(wasBookmarked ? 'تمت إزالة الإشارة المرجعية' : 'تم حفظ الإشارة المرجعية')
  }

  // When arriving with ?ayah=N (e.g. from the bookmark card), bring that ayah
  // into view once the surah has rendered.
  const requestedAyah = searchParams.get('ayah')
  useEffect(() => {
    if (!surah || !requestedAyah) return

    document.getElementById(`ayah-${Number(requestedAyah)}`)?.scrollIntoView({ behavior: 'smooth', block: 'center' })
  }, [surah, requestedAyah])

  return (
    <AsyncContent pending={isFetching} error={error} loadingMessage="جاري تحميل السورة...">
      {surah && (
        <Page className={styles.page}>
          <Heading
            title={normalizeQuranicText(surah.data.name)}
            subtitle={`عدد الآيات: ${toArabicNumerals(surah.data.numberOfAyahs)} آية - سورة ${revelationLabel}`}
            share
          />

          {online && <QuranPlayer ref={playerRef} />}

          <div className={`${styles.ayat} font-quran mb-4`}>
            {surahNumber !== 9 && <span className={styles.basmallah}>بِسْمِ ٱللَّهِ ٱلرَّحۡمَـٰنِ ٱلرَّحِیمِ</span>}

            {ayat.map((ayah, index) => (
              <Fragment key={ayah.number}>
                <span
                  id={`ayah-${ayah.numberInSurah}`}
                  className={`ayah ${currentAyah?.ayah === ayah.numberInSurah ? styles.currentAyah : ''} ${
                    isBookmarkedVerse(ayah) ? styles.bookmarkedAyah : ''
                  }`}
                  onClick={() => openActions(ayah)}
                  title={`خيارات الآية ${toArabicNumerals(ayah.numberInSurah)}`}
                >
                  {ayah.text}
                </span>
                <span className="ayah-number" aria-hidden="true">
                  {toArabicNumerals(ayah.numberInSurah)}
                </span>
                {index < ayat.length - 1 && ayah.page !== ayat[index + 1].page && (
                  <div className={styles.pageSeparator}>
                    <span className={styles.pageNumber}>{toArabicNumerals(ayah.page)}</span>
                  </div>
                )}
              </Fragment>
            ))}
          </div>

          <div className="d-flex justify-content-center align-items-center gap-2">
            <Link
              to={ROUTES.quranSurah(surahNumber - 1)}
              className={`btn btn-flat d-inline-flex align-items-center gap-2 ${surahNumber === FIRST_SURAH ? 'disabled' : ''}`}
            >
              <IconArrowRight size="1.25rem" />
              <span>السابقة</span>
            </Link>

            <BackButton to={ROUTES.quran} buttonClass="btn-primary" />

            <Link
              to={ROUTES.quranSurah(surahNumber + 1)}
              className={`btn btn-flat d-inline-flex align-items-center gap-2 ${surahNumber === LAST_SURAH ? 'disabled' : ''}`}
            >
              <span>التالية</span>
              <IconArrowLeft size="1.25rem" />
            </Link>
          </div>

          <AyahActionSheet
            show={showActions}
            ayah={activeAyah}
            surahName={surah.data.name}
            online={online}
            bookmarked={!!activeAyah && isBookmarkedVerse(activeAyah)}
            onRecite={() => playerRef.current?.seekToAyah(activeAyah?.numberInSurah)}
            onTafseer={openTafseer}
            onBookmark={handleBookmark}
            onClose={() => setShowActions(false)}
          />

          <TafseerSheet
            show={showTafseer}
            ayah={tafseerAyah}
            hasPrev={tafseerIndex > 0}
            hasNext={tafseerIndex >= 0 && tafseerIndex < ayat.length - 1}
            onPrev={() => stepTafseer(-1)}
            onNext={() => stepTafseer(1)}
            onClose={() => setShowTafseer(false)}
          />
        </Page>
      )}
    </AsyncContent>
  )
}

// src/views/QuranSurahView.vue
<script setup>
import { computed, ref, watch } from 'vue'
import { useOnline } from '@vueuse/core'
import { useRouteParams } from '@vueuse/router'

import Page from '@/components/Layout/Page.vue'
import Heading from '@/components/Heading.vue'
import BackButton from '@/components/BackButton.vue'
import LoadingState from '@/components/LoadingState.vue'
import ErrorState from '@/components/ErrorState.vue'
import OfflineState from '@/components/OfflineState.vue'
import AudioPlayer from '@/components/QuranPlayer.vue'
import { useQuranStore } from '@/stores/quran'
import { useMeta } from '@/utilities/head'
import { toArabicNumerals, removeBismillah } from '@/utilities/arabic'
import { useQuranService } from '@/services/quranService'

const online = useOnline()
const surahId = useRouteParams('surah')
const quranStore = useQuranStore()
const { fetchSurah } = useQuranService()

const surah = ref(null)
const isFetching = ref(true)
const error = ref(null)
const playerRef = ref(null)

async function loadSurah() {
  isFetching.value = true
  error.value = null

  try {
    surah.value = await fetchSurah(surahId.value)
    if (online.value && surah.value) {
      await quranStore.loadSurahAudio(surah.value.data.number, surah.value.data.name)
    }
  } catch (e) {
    error.value = e
  } finally {
    isFetching.value = false
  }
}

loadSurah()

watch(surah, (val) => {
  if (val) {
    useMeta({
      title: val.data.name,
      description: `قراءة وتلاوة سورة ${val.data.name} - ${toArabicNumerals(val.data.numberOfAyahs)} آية - سورة ${val.data.revelationType === 'Meccan' ? 'مكية' : 'مدنية'}`,
      keywords: ['قرآن', 'سورة', val.data.name, 'تلاوة', 'قراءة', 'رفيق'],
    })
  }
})

const ayat = computed(() => {
  if (surah.value) {
    let ayat = surah.value.data.ayahs

    if (surah.value.data.number === 1) {
      ayat = ayat.slice(1)
    }

    return ayat.map((ayah) => {
      const text = (ayah.numberInSurah === 1 ? removeBismillah(ayah.text) : ayah.text).trim()

      return {
        ...ayah,
        text,
      }
    })
  }

  return []
})

const playVerse = (verse) => {
  if (!playerRef.value) return
  playerRef.value.seekToAyah(verse.numberInSurah)
}

const isCurrentVerse = (verse) => {
  const currentAyah = quranStore.currentAyah
  if (!currentAyah || !surah.value) return false
  return currentAyah.ayah === verse.numberInSurah
}
</script>

<template>
  <Page v-if="isFetching">
    <LoadingState message="جاري تحميل السورة..." />
  </Page>

  <Page v-else-if="error">
    <OfflineState v-if="!online" />
    <ErrorState :code="500" message="حدث خطأ أثناء تحميل البيانات، برجاء المحاولة في وقت لاحق." v-else />
  </Page>

  <Page class="quran-page" v-else-if="surah">
    <Heading
      :title="surah.data.name"
      :subtitle="`عدد الآيات: ${toArabicNumerals(surah.data.numberOfAyahs)} آية - سورة ${surah.data.revelationType === 'Meccan' ? 'مكية' : 'مدنية'}`"
      :share="true"
    />

    <!-- Audio Player -->
    <AudioPlayer v-if="online" ref="playerRef" />

    <div class="ayat font-quran mb-4">
      <span class="basmallah" v-if="surahId != 9">بِسْمِ ٱللَّهِ ٱلرَّحۡمَـٰنِ ٱلرَّحِیمِ</span>

      <template v-for="(ayah, index) in ayat" :key="ayah.number">
        <span
          class="ayah clickable-ayah"
          :class="{ 'current-ayah': isCurrentVerse(ayah) }"
          @click="playVerse(ayah)"
          :title="`تشغيل الآية ${toArabicNumerals(ayah.numberInSurah)}`"
          >{{ ayah.text }}</span
        >
        <span class="ayah-number" aria-hidden="true">{{ toArabicNumerals(ayah.numberInSurah) }}</span>
        <div v-if="index < ayat.length - 1 && ayah.page !== ayat[index + 1].page" class="page-separator">
          <span class="page-number">{{ toArabicNumerals(ayah.page) }}</span>
        </div>
      </template>
    </div>

    <div class="d-flex justify-content-center">
      <BackButton :to="{ name: 'quran' }" button-class="btn-primary" />
    </div>
  </Page>
</template>

<style lang="scss" scoped>
@import '@/assets/scss/quran.css';

.quran-page {
  display: flex;
  flex-direction: column;
  gap: 10px;
  max-width: 700px;

  .ayat {
    padding: 1rem;
    border-radius: 5px;
    border: 1px solid var(--bs-border-color);
    text-align: justify;
    text-align-last: center;
    text-justify: inter-word;

    .basmallah {
      display: block;
      font-size: 2rem;
      line-height: 2.5;
      text-align: center;
      margin-bottom: 1rem;
    }

    .ayah,
    .ayah-number {
      line-height: 2;
      font-size: 1.625rem;
      margin-bottom: 0.75rem;
    }

    .page-separator {
      display: flex;
      align-items: center;
      width: 100%;
      margin: 2rem 0;

      &::before,
      &::after {
        content: '';
        flex: 1;
        border-bottom: 1px solid var(--bs-border-color);
      }

      .page-number {
        padding: 0.15rem 0.75rem;
        font-size: 0.875rem;
        color: var(--bs-gray-600);
        font-family: 'IBM Plex Sans Arabic', sans-serif;
        white-space: nowrap;
        border: 1px solid var(--bs-border-color);
        border-radius: 999px;
      }
    }

    .clickable-ayah {
      cursor: pointer;
    }

    .current-ayah {
      background-color: var(--bs-secondary-bg);
    }
  }
}
</style>
