// src/features/settings/components/SettingsAutoUpdate.vue
<script setup>
import { storeToRefs } from 'pinia'
import { IconRefresh } from '@tabler/icons-vue'
import { useAppStore } from '@/app/stores/app'
import SettingsToggle from './SettingsToggle.vue'

const appStore = useAppStore()
const { autoUpdateServiceWorker } = storeToRefs(appStore)
</script>

<template>
  <SettingsToggle
    v-model="autoUpdateServiceWorker"
    title="التحديث التلقائي"
    description="عند التعطيل سيتم عرض إشعار لتحديث التطبيق"
    :icon="IconRefresh"
    label="تفعيل التحديث التلقائي"
  />
</template>

// src/features/settings/components/SettingsAutoUpdate.jsx
import { IconRefresh } from '@tabler/icons-react'

import SettingsSection from './SettingsSection'
import SettingsToggle from './SettingsToggle'
import { useAppStore } from '@/app/stores/app'

export default function SettingsAutoUpdate() {
  const autoUpdateServiceWorker = useAppStore((state) => state.autoUpdateServiceWorker)
  const setAutoUpdateServiceWorker = useAppStore((state) => state.setAutoUpdateServiceWorker)

  return (
    <SettingsSection
      title="التحديث التلقائي"
      description="عند التعطيل سيتم عرض إشعار لتحديث التطبيق"
      icon={IconRefresh}
      actions={
        <SettingsToggle
          checked={autoUpdateServiceWorker}
          onChange={setAutoUpdateServiceWorker}
          label="تفعيل التحديث التلقائي"
        />
      }
    />
  )
}
