// src/features/settings/components/SettingsZekrLeaveConfirmation.vue
<script setup>
import { storeToRefs } from 'pinia'
import { IconDoorExit } from '@tabler/icons-vue'
import { useAppStore } from '@/app/stores/app'
import SettingsToggle from './SettingsToggle.vue'

const appStore = useAppStore()
const { zekrConfirmOnLeave } = storeToRefs(appStore)
</script>

<template>
  <SettingsToggle
    v-model="zekrConfirmOnLeave"
    title="تأكيد المغادرة"
    description="يطلب تأكيداً قبل مغادرة الذكر إذا لم يكتمل"
    :icon="IconDoorExit"
    label="تفعيل تأكيد المغادرة عند وجود أذكار غير مكتملة"
  />
</template>

// src/features/settings/components/SettingsZekrLeaveConfirmation.jsx
import { IconDoorExit } from '@tabler/icons-react'

import SettingsSection from './SettingsSection'
import SettingsToggle from './SettingsToggle'
import { useAppStore } from '@/app/stores/app'

export default function SettingsZekrLeaveConfirmation() {
  const zekrConfirmOnLeave = useAppStore((state) => state.zekrConfirmOnLeave)
  const setZekrConfirmOnLeave = useAppStore((state) => state.setZekrConfirmOnLeave)

  return (
    <SettingsSection
      title="تأكيد المغادرة"
      description="يطلب تأكيداً قبل مغادرة الذكر إذا لم يكتمل"
      icon={IconDoorExit}
      actions={
        <SettingsToggle
          checked={zekrConfirmOnLeave}
          onChange={setZekrConfirmOnLeave}
          label="تفعيل تأكيد المغادرة عند وجود أذكار غير مكتملة"
        />
      }
    />
  )
}
