// src/features/settings/components/SettingsZekrProgress.jsx
import { IconDeviceFloppy } from '@tabler/icons-react'

import SettingsSection from './SettingsSection'
import SettingsToggle from './SettingsToggle'
import { useAppStore } from '@/app/stores/app'

export default function SettingsZekrProgress() {
  const zekrSaveProgress = useAppStore((state) => state.zekrSaveProgress)
  const setZekrSaveProgress = useAppStore((state) => state.setZekrSaveProgress)

  return (
    <SettingsSection
      title="حفظ التقدم"
      description="يحفظ تقدمك في كل قسم من الأذكار ويعيد ضبطه يومياً"
      icon={IconDeviceFloppy}
      actions={
        <SettingsToggle checked={zekrSaveProgress} onChange={setZekrSaveProgress} label="تفعيل حفظ تقدم الأذكار" />
      }
    />
  )
}

// src/features/settings/components/SettingsZekrProgress.vue
<script setup>
import { storeToRefs } from 'pinia'
import { IconDeviceFloppy } from '@tabler/icons-vue'
import { useAppStore } from '@/app/stores/app'
import SettingsToggle from './SettingsToggle.vue'

const appStore = useAppStore()
const { zekrSaveProgress } = storeToRefs(appStore)
</script>

<template>
  <SettingsToggle
    v-model="zekrSaveProgress"
    title="حفظ التقدم"
    description="يحفظ تقدمك في كل قسم من الأذكار ويعيد ضبطه يومياً"
    :icon="IconDeviceFloppy"
    label="تفعيل حفظ تقدم الأذكار"
  />
</template>
