// src/features/settings/components/SettingsZekrMoveNext.jsx
import { IconArrowDownCircle } from '@tabler/icons-react'

import SettingsSection from './SettingsSection'
import SettingsToggle from './SettingsToggle'
import { useAppStore } from '@/app/stores/app'

export default function SettingsZekrMoveNext() {
  const zekrMoveNextOnComplete = useAppStore((state) => state.zekrMoveNextOnComplete)
  const setZekrMoveNextOnComplete = useAppStore((state) => state.setZekrMoveNextOnComplete)

  return (
    <SettingsSection
      title="الانتقال للذكر التالي"
      description="ينقلك تلقائياً إلى الذكر التالي عند إكمال العدد المطلوب"
      icon={IconArrowDownCircle}
      actions={
        <SettingsToggle
          checked={zekrMoveNextOnComplete}
          onChange={setZekrMoveNextOnComplete}
          label="تفعيل الانتقال التلقائي للذكر التالي"
        />
      }
    />
  )
}

// src/features/settings/components/SettingsZekrMoveNext.vue
<script setup>
import { storeToRefs } from 'pinia'
import { IconArrowDownCircle } from '@tabler/icons-vue'
import { useAppStore } from '@/app/stores/app'
import SettingsToggle from './SettingsToggle.vue'

const appStore = useAppStore()
const { zekrMoveNextOnComplete } = storeToRefs(appStore)
</script>

<template>
  <SettingsToggle
    v-model="zekrMoveNextOnComplete"
    title="الانتقال للذكر التالي"
    description="ينقلك تلقائياً إلى الذكر التالي عند إكمال العدد المطلوب"
    :icon="IconArrowDownCircle"
    label="تفعيل الانتقال التلقائي للذكر التالي"
  />
</template>
