// src/features/settings/components/SettingsZekrVibration.vue
<script setup>
import { computed } from 'vue'
import { storeToRefs } from 'pinia'
import { IconDeviceMobileVibration } from '@tabler/icons-vue'
import { useAppStore } from '@/app/stores/app'
import { toArabicNumerals } from '@/shared/utils/arabic'
import SettingsSection from './SettingsSection.vue'

const appStore = useAppStore()
const { zekrVibrationEnabled, zekrVibrationIntensity } = storeToRefs(appStore)

const vibrationValueLabel = computed(() => toArabicNumerals(zekrVibrationIntensity.value))
</script>

<template>
  <SettingsSection
    title="الاهتزاز عند الانتهاء"
    description="يعمل على الأجهزة والمتصفحات التي تدعم الاهتزاز"
    :icon="IconDeviceMobileVibration"
  >
    <template #actions>
      <div class="form-check form-switch m-0">
        <input v-model="zekrVibrationEnabled" class="form-check-input" type="checkbox" />
      </div>
    </template>

    <div v-if="zekrVibrationEnabled" class="p-3 border rounded">
      <div class="d-flex justify-content-between align-items-center gap-3 mb-2">
        <span>قوة الاهتزاز</span>
        <small class="text-muted">{{ vibrationValueLabel }} مللي ثانية</small>
      </div>

      <input v-model.number="zekrVibrationIntensity" class="form-range" type="range" min="20" max="250" step="10" />

      <div class="d-flex justify-content-between text-muted">
        <small>خفيف</small>
        <small>قوي</small>
      </div>
    </div>
  </SettingsSection>
</template>

// src/features/settings/components/SettingsZekrVibration.jsx
import { IconDeviceMobileVibration } from '@tabler/icons-react'

import SettingsSection from './SettingsSection'
import SettingsToggle from './SettingsToggle'
import { useAppStore } from '@/app/stores/app'
import { toArabicNumerals } from '@/shared/utils/arabic'

export default function SettingsZekrVibration() {
  const enabled = useAppStore((state) => state.zekrVibrationEnabled)
  const setEnabled = useAppStore((state) => state.setZekrVibrationEnabled)
  const intensity = useAppStore((state) => state.zekrVibrationIntensity)
  const setIntensity = useAppStore((state) => state.setZekrVibrationIntensity)

  return (
    <SettingsSection
      title="الاهتزاز عند الانتهاء"
      description="يعمل على الأجهزة والمتصفحات التي تدعم الاهتزاز"
      icon={IconDeviceMobileVibration}
      actions={<SettingsToggle checked={enabled} onChange={setEnabled} label="تفعيل الاهتزاز عند إتمام الذكر" />}
    >
      {enabled && (
        <div className="p-3 border rounded">
          <div className="d-flex justify-content-between align-items-center gap-3 mb-2">
            <span>قوة الاهتزاز</span>
            <small className="text-muted">{toArabicNumerals(intensity)} مللي ثانية</small>
          </div>

          <input
            value={intensity}
            onChange={(event) => setIntensity(Number(event.target.value))}
            className="form-range"
            type="range"
            min="20"
            max="250"
            step="10"
            aria-label="قوة الاهتزاز"
          />

          <div className="d-flex justify-content-between text-muted">
            <small>خفيف</small>
            <small>قوي</small>
          </div>
        </div>
      )}
    </SettingsSection>
  )
}
