// src/app/App.vue
<script setup>
import { RouterView, useRoute } from 'vue-router'
import Navbar from '@/layout/Navbar.vue'
import Footer from '@/layout/Footer.vue'
import TabBar from '@/layout/TabBar.vue'
import { IconWifiOff } from '@tabler/icons-vue'
import { computed, ref, watch } from 'vue'
import { useOnline } from '@vueuse/core'
import { Toaster, toast } from 'vue-sonner'
import { useThemeStore } from '@/app/stores/theme'
import { useAppStore } from '@/app/stores/app'
import { registerSW } from 'virtual:pwa-register'

// Network status detection
const online = useOnline()
const themeStore = useThemeStore()
const appStore = useAppStore()

const route = useRoute()
const isEmbedRoute = computed(() => route.path.startsWith('/embed'))

// Offline banner visibility
const showOfflineBanner = ref(true)

// Reset banner when connection is restored
watch(online, (isOnline) => {
  if (isOnline) {
    showOfflineBanner.value = true
  }
})

const updateSW = registerSW({
  onNeedRefresh() {
    if (isEmbedRoute.value || appStore.autoUpdateServiceWorker) {
      updateSW(true)
      return
    }

    toast('يتوفر تحديث جديد للتطبيق.', {
      action: {
        label: 'تحديث الآن',
        onClick: () => updateSW(true),
      },
      duration: Infinity,
    })
  },
})
</script>

<template>
  <div :class="['app-shell', { 'main-content-embed': isEmbedRoute }]">
    <!-- Offline indicator -->
    <div v-if="!online && showOfflineBanner" class="offline-banner">
      <div class="container">
        <div class="d-flex align-items-center text-white">
          <IconWifiOff class="me-2" size="1.25rem" />
          <span>لا يوجد اتصال بالإنترنت</span>

          <button
            type="button"
            class="btn-close btn-close-white ms-auto"
            aria-label="Close"
            @click="showOfflineBanner = false"
          ></button>
        </div>
      </div>
    </div>

    <!-- Desktop Navbar -->
    <Navbar class="d-none d-md-block" v-if="!isEmbedRoute" />

    <!-- Main Content -->
    <div class="main-content">
      <RouterView />
    </div>

    <!-- Desktop Footer -->
    <Footer class="d-none d-md-block" v-if="!isEmbedRoute" />

    <!-- Mobile TabBar -->
    <TabBar class="d-block d-md-none" v-if="!isEmbedRoute" />
  </div>

  <!-- Toast -->
  <Toaster
    :theme="themeStore.mode"
    position="bottom-left"
    offset="20px"
    :toast-options="{
      style: {
        gap: '20px',
        fontFamily: 'IBM Plex Sans Arabic, sans-serif',
      },
    }"
  />
</template>

<style lang="scss" scoped>
.offline-banner {
  min-height: 50px;
  background-color: #dc3545;
  padding: 0.75rem 0;
  position: sticky;
  top: 0;
  z-index: 1030;
  animation: slideDown 0.3s ease-out;
}

.offline-banner + .navbar {
  top: 50px; /* Adjust navbar position when offline banner is visible */
}

.main-content {
  min-height: calc(100vh - var(--navbar-height)); /* Adjust for navbar and footer on desktop */
  padding-bottom: var(--navbar-height);
}

/* Embed adjustments */
.main-content-embed .main-content {
  min-height: 100vh;
  padding-bottom: unset;
  display: flex;
  align-items: center;
  justify-content: center;
}

/* Desktop adjustments */
@media (min-width: 992px) {
  .main-content {
    min-height: calc(100vh - 400px);
    padding-bottom: 0;
  }
}

@keyframes slideDown {
  from {
    transform: translateY(-100%);
    opacity: 0;
  }
  to {
    transform: translateY(0);
    opacity: 1;
  }
}
</style>

// src/app/App.jsx
import { useEffect, useState } from 'react'
import { Outlet, ScrollRestoration, useLocation } from 'react-router-dom'
import { IconWifiOff } from '@tabler/icons-react'
import { Toaster } from 'sonner'

import Navbar from '@/layout/Navbar'
import Footer from '@/layout/Footer'
import TabBar from '@/layout/TabBar'
import { isEmbedPath } from '@/app/router/routes'
import { useRouteEffects } from '@/app/router/useRouteEffects'
import { useApplyTheme, useResolvedThemeMode } from '@/app/stores/theme'
import { useRadioNotifications } from '@/features/radio/hooks/useRadioNotifications'
import { useOnline } from '@/shared/hooks/useOnline'

// The app shell: chrome around the routed page, plus the effects that have to
// run for every route.
export default function App() {
  const online = useOnline()
  const isEmbed = isEmbedPath(useLocation().pathname)
  const themeMode = useResolvedThemeMode()

  useApplyTheme()
  useRouteEffects()
  useRadioNotifications()

  const [showOfflineBanner, setShowOfflineBanner] = useState(true)

  // Offer the banner again the next time the connection drops.
  useEffect(() => {
    const restoreBanner = () => setShowOfflineBanner(true)

    window.addEventListener('online', restoreBanner)
    return () => window.removeEventListener('online', restoreBanner)
  }, [])

  return (
    <>
      <div className={`app-shell ${isEmbed ? 'main-content-embed' : ''}`}>
        {!online && showOfflineBanner && (
          <div className="offline-banner">
            <div className="container">
              <div className="d-flex align-items-center text-white">
                <IconWifiOff className="me-2" size="1.25rem" />
                <span>لا يوجد اتصال بالإنترنت</span>

                <button
                  type="button"
                  className="btn-close btn-close-white ms-auto"
                  aria-label="Close"
                  onClick={() => setShowOfflineBanner(false)}
                ></button>
              </div>
            </div>
          </div>
        )}

        {!isEmbed && <Navbar className="d-none d-md-block" />}

        <div className="main-content">
          <Outlet />
        </div>

        {!isEmbed && <Footer className="d-none d-md-block" />}

        {!isEmbed && <TabBar className="d-block d-md-none" />}
      </div>

      <ScrollRestoration />

      <Toaster
        theme={themeMode}
        position="bottom-left"
        offset="20px"
        toastOptions={{
          style: {
            gap: '20px',
            fontFamily: 'Thmanyah Sans, sans-serif',
          },
        }}
      />
    </>
  )
}
