// src/features/settings/views/SettingsView.jsx
import { Link, useParams } from 'react-router-dom'
import {
  IconPalette,
  IconClockHour4,
  IconBook2,
  IconSparkles,
  IconDeviceMobile,
  IconCloudDownload,
} from '@tabler/icons-react'

import Page from '@/layout/Page'
import Heading from '@/shared/ui/Heading'

import SettingsTheme from '../components/SettingsTheme'
import SettingsFontSize from '../components/SettingsFontSize'
import SettingsPrayerTimes from '../components/SettingsPrayerTimes'
import SettingsReciter from '../components/SettingsReciter'
import SettingsTafseer from '../components/SettingsTafseer'
import SettingsDownloadAssets from '../components/SettingsDownloadAssets'
import SettingsAutoUpdate from '../components/SettingsAutoUpdate'
import SettingsNotifications from '../components/SettingsNotifications'
import SettingsImportExport from '../components/SettingsImportExport'
import SettingsZekrMoveNext from '../components/SettingsZekrMoveNext'
import SettingsZekrProgress from '../components/SettingsZekrProgress'
import SettingsZekrLeaveConfirmation from '../components/SettingsZekrLeaveConfirmation'
import SettingsZekrVibration from '../components/SettingsZekrVibration'
import { ROUTES } from '@/app/router/routes'
import styles from './SettingsView.module.scss'

const TABS = [
  {
    id: 'appearance',
    label: 'المظهر',
    icon: IconPalette,
    sections: [SettingsTheme, SettingsFontSize],
  },
  {
    id: 'prayer',
    label: 'مواقيت الصلاة',
    icon: IconClockHour4,
    sections: [SettingsPrayerTimes],
  },
  {
    id: 'quran',
    label: 'القرآن',
    icon: IconBook2,
    sections: [SettingsReciter, SettingsTafseer],
  },
  {
    id: 'azkar',
    label: 'الأذكار',
    icon: IconSparkles,
    sections: [SettingsZekrMoveNext, SettingsZekrProgress, SettingsZekrLeaveConfirmation, SettingsZekrVibration],
  },
  {
    id: 'app',
    label: 'التطبيق',
    icon: IconDeviceMobile,
    sections: [SettingsAutoUpdate, SettingsNotifications, SettingsImportExport],
  },
  {
    id: 'downloads',
    label: 'التنزيلات',
    icon: IconCloudDownload,
    sections: [SettingsDownloadAssets],
  },
]

export default function SettingsView() {
  const { tab } = useParams()
  const activeTab = TABS.find((item) => item.id === tab) ?? TABS[0]

  return (
    <Page>
      <Heading className="mb-4" title="الإعدادات" subtitle="تعديل الإعدادات المختلفة للتطبيق" />

      <div className={styles.layout}>
        <nav className={`${styles.nav} tab-pills`} aria-label="أقسام الإعدادات">
          {TABS.map((item) => (
            <Link
              key={item.id}
              to={ROUTES.settingsTab(item.id)}
              className={`${styles.navItem} tab-pill ${activeTab.id === item.id ? 'active' : ''}`}
            >
              <item.icon size={20} />
              <span>{item.label}</span>
            </Link>
          ))}
        </nav>

        <div className={styles.content}>
          <div className={styles.stack}>
            {activeTab.sections.map((Section, index) => (
              <Section key={index} />
            ))}
          </div>
        </div>
      </div>
    </Page>
  )
}

// src/features/settings/SettingsView.vue
<script setup>
import { computed } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import {
  IconPalette,
  IconClockHour4,
  IconBook2,
  IconSparkles,
  IconDeviceMobile,
  IconCloudDownload,
} from '@tabler/icons-vue'

import Page from '@/layout/Page.vue'
import Heading from '@/shared/ui/Heading.vue'

import SettingsTheme from './partials/SettingsTheme.vue'
import SettingsFontSize from './partials/SettingsFontSize.vue'
import SettingsPrayerTimes from './partials/SettingsPrayerTimes.vue'
import SettingsReciter from './partials/SettingsReciter.vue'
import SettingsZekr from './partials/SettingsZekr.vue'
import SettingsAppUpdates from './partials/SettingsAppUpdates.vue'
import SettingsDownloadAssets from './partials/SettingsDownloadAssets.vue'

const tabs = [
  { id: 'appearance', label: 'المظهر', icon: IconPalette },
  { id: 'prayer', label: 'مواقيت الصلاة', icon: IconClockHour4 },
  { id: 'quran', label: 'القرآن', icon: IconBook2 },
  { id: 'azkar', label: 'الأذكار', icon: IconSparkles },
  { id: 'app', label: 'التطبيق', icon: IconDeviceMobile },
  { id: 'downloads', label: 'التنزيلات', icon: IconCloudDownload },
]

const route = useRoute()
const activeTab = computed(() => route.params.tab || 'appearance')
</script>

<template>
  <Page>
    <Heading class="mb-4" title="الإعدادات" subtitle="تعديل الإعدادات المختلفة للتطبيق" />

    <div class="settings-layout">
      <!-- Tabs navigation -->
      <nav class="settings-nav tab-pills" aria-label="أقسام الإعدادات">
        <RouterLink
          v-for="tab in tabs"
          :key="tab.id"
          :to="{ name: 'settings', params: { tab: tab.id } }"
          class="settings-nav-item tab-pill"
          :class="{ active: activeTab === tab.id }"
        >
          <component :is="tab.icon" :size="20" />
          <span>{{ tab.label }}</span>
        </RouterLink>
      </nav>

      <!-- Tab content -->
      <div class="settings-content">
        <div v-if="activeTab === 'appearance'" class="settings-stack">
          <SettingsTheme />
          <SettingsFontSize />
        </div>

        <SettingsPrayerTimes v-else-if="activeTab === 'prayer'" />

        <SettingsReciter v-else-if="activeTab === 'quran'" />

        <div v-else-if="activeTab === 'azkar'">
          <SettingsZekr />
        </div>

        <SettingsAppUpdates v-else-if="activeTab === 'app'" />

        <SettingsDownloadAssets v-else-if="activeTab === 'downloads'" />
      </div>
    </div>
  </Page>
</template>

<style scoped>
.settings-layout {
  display: grid;
  grid-template-columns: 240px 1fr;
  gap: 1.5rem;
  align-items: start;
}

/* Navigation — sidebar on desktop */
.settings-nav {
  flex-direction: column;
  gap: 0.25rem;
  overflow-x: visible;
  padding: 0;
  margin: 0;
  position: sticky;
  top: calc(var(--navbar-height) + 1rem);
}

.settings-nav-item {
  width: 100%;
  flex-shrink: 1;
  padding-block: 0.7rem;
  border-color: transparent;
  font-size: 0.9rem;
}

.settings-content {
  min-width: 0;
}

.settings-stack {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

/* Mobile — horizontal scrollable pills */
@media (max-width: 767.98px) {
  .settings-layout {
    grid-template-columns: 1fr;
    gap: 1rem;
  }

  .settings-nav {
    flex-direction: row;
    position: static;
    gap: 0.5rem;
    overflow-x: auto;
    padding-top: 0;
    padding-bottom: 0.35rem;
    margin-inline: -0.25rem;
    padding-inline: 0.25rem;
  }

  .settings-nav-item {
    width: auto;
    flex-shrink: 0;
    border-color: var(--bs-border-color);
    padding: 0.5rem 0.9rem;
    font-size: 0.85rem;
  }

  .settings-nav-item.active {
    border-color: transparent;
  }
}
</style>
