// src/features/prayers/components/SunnahPrayers.jsx
import PrayerIcon from '@/features/prayers/components/icons/PrayerIcon'
import { toArabicNumerals } from '@/shared/utils/arabic'
import styles from './SunnahPrayers.module.scss'

const PRAYERS = [
  { name: 'الفجر', before: 2, after: 0, icon: 'fajr' },
  { name: 'الظهر', before: 4, after: 4, icon: 'dhuhr' },
  { name: 'العصر', before: 0, after: 0, icon: 'asr' },
  { name: 'المغرب', before: 0, after: 2, icon: 'maghrib' },
  { name: 'العشاء', before: 0, after: 2, icon: 'isha' },
]

const formatRakaa = (value) => {
  if (value === 0) return '—'
  if (value === 2) return 'ركعتان'
  return `${toArabicNumerals(value)} ركعات`
}

const mutedWhenNone = (value) => (value === 0 ? 'text-body-secondary' : '')

export default function SunnahPrayers({ className = '' }) {
  return (
    <div className={className}>
      {/* List layout (below lg) */}
      <div className="d-lg-none">
        <div className="d-flex justify-content-end px-3 pb-1 small text-body-secondary">
          <span className={styles.rakaaColumn}>قبل</span>
          <span className={styles.rakaaColumn}>بعد</span>
        </div>
        <div className="d-flex flex-column gap-1">
          {PRAYERS.map((prayer) => (
            <div
              key={prayer.name}
              className="d-flex align-items-center justify-content-between px-3 py-2 rounded-2 small border"
            >
              <div className="d-flex align-items-center gap-2">
                <span className={`${styles.iconContainer} text-secondary`}>
                  <PrayerIcon name={prayer.icon} />
                </span>
                <span className="fw-semibold">{prayer.name}</span>
              </div>
              <div className="d-flex">
                <span className={`${styles.rakaaColumn} fw-semibold ${mutedWhenNone(prayer.before)}`}>
                  {formatRakaa(prayer.before)}
                </span>
                <span className={`${styles.rakaaColumn} fw-semibold ${mutedWhenNone(prayer.after)}`}>
                  {formatRakaa(prayer.after)}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Cards layout (lg and up) */}
      <div className="d-none d-lg-flex row row-cols-lg-5 g-2">
        {PRAYERS.map((prayer) => (
          <div key={prayer.name} className="col">
            <div className="card h-100">
              <div className="card-body p-3">
                <div className="d-flex align-items-center gap-2 mb-3">
                  <span className="icon-circle text-secondary">
                    <PrayerIcon name={prayer.icon} />
                  </span>
                  <h3 className="card-title mb-0 fs-6 fw-semibold">{prayer.name}</h3>
                </div>

                <div className="row g-0 text-center small">
                  <div className="col-6 pe-2">
                    <div className="text-body-secondary mb-1">قبل</div>
                    <div className={`fw-semibold ${mutedWhenNone(prayer.before)}`}>{formatRakaa(prayer.before)}</div>
                  </div>
                  <div className="col-6 ps-2 border-start">
                    <div className="text-body-secondary mb-1">بعد</div>
                    <div className={`fw-semibold ${mutedWhenNone(prayer.after)}`}>{formatRakaa(prayer.after)}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

// src/components/SunnahPrayers.vue
<script setup>
import FajrIcon from '@/components/icons/Prayers/Fajr.vue'
import DuhurIcon from '@/components/icons/Prayers/Duhur.vue'
import MaghribIcon from '@/components/icons/Prayers/Maghrib.vue'
import IshaaIcon from '@/components/icons/Prayers/Ishaa.vue'
import { IconArrowBarToUp, IconArrowBarToDown } from '@tabler/icons-vue'
import { toArabicNumerals } from '@/utilities/arabic'

const prayers = [
  {
    name: 'الفجر',
    before: 2,
    after: '-',
    icon: FajrIcon,
  },
  {
    name: 'الظهر',
    before: 4,
    after: 4,
    icon: DuhurIcon,
  },
  {
    name: 'المغرب',
    before: '-',
    after: 2,
    icon: MaghribIcon,
  },
  {
    name: 'العشاء',
    before: '-',
    after: 2,
    icon: IshaaIcon,
  },
]

const formatRakaa = (value) => {
  if (value === '-') return '-'
  if (value === 2) return 'ركعتان'
  return `${toArabicNumerals(value)} ركعات`
}
</script>

<template>
  <div class="row row-cols-2 row-cols-lg-4 g-2">
    <div v-for="(prayer, index) in prayers" :key="index" class="col">
      <div class="card h-100">
        <div class="card-body d-flex align-items-start gap-2 p-2">
          <span class="icon-container">
            <component :is="prayer.icon" />
          </span>
          <div class="flex-grow-1">
            <h5 class="card-title mb-2 fs-5">{{ prayer.name }}</h5>
            <div class="stacked-info small">
              <div class="info-block">
                <span class="info-label">
                  <IconArrowBarToUp />
                  قبل
                </span>
                <span class="info-value">{{ formatRakaa(prayer.before) }}</span>
              </div>
              <div class="info-block">
                <span class="info-label">
                  <IconArrowBarToDown />
                  بعد
                </span>
                <span class="info-value">{{ formatRakaa(prayer.after) }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.icon-container {
  display: grid;
  place-items: center;
  width: 34px;
  height: 34px;
  border-radius: 50%;
  background-color: transparent;
  border: 1px solid var(--bs-border-color);

  :deep(svg) {
    width: 20px;
    height: 20px;
  }
}

.stacked-info {
  display: grid;
  gap: 4px;
}

.info-block {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 6px 8px;
  background-color: var(--bs-tertiary-bg);
  border-radius: var(--bs-border-radius);
}

.info-label {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  color: var(--bs-secondary-color);

  :deep(svg) {
    width: 16px;
    height: 16px;
  }
}

.info-value {
  font-weight: 600;
}
</style>
