// src/app/views/NotFoundView.vue
<script setup>
import Page from '@/layout/Page.vue'
import ErrorState from '@/shared/ui/ErrorState.vue'
</script>

<template>
  <!-- A whole-page fallback sits near the middle of the phone rather than
       clinging under the navbar — the same framing the async fallbacks use. -->
  <Page class="grid min-h-[55vh] place-items-center">
    <ErrorState code="404" message="الصفحة التي تبحث عنها غير موجودة." />
  </Page>
</template>

// src/app/views/NotFoundView.jsx
import Page from '@/layout/Page'
import ErrorState from '@/shared/ui/ErrorState'
import { usePageMeta } from '@/shared/hooks/usePageMeta'
import { NOT_FOUND_META } from '@/app/views/notFoundMeta'

export default function NotFoundView() {
  // Set here (not only on the '*' route) so a 404 raised by a route loader
  // gets the same meta.
  usePageMeta(NOT_FOUND_META)

  return (
    <Page>
      <ErrorState code={404} message="الصفحة التي تبحث عنها غير موجودة." />
    </Page>
  )
}
