// src/app/views/PrivacyPolicyView.jsx
import Page from '@/layout/Page'
import Heading from '@/shared/ui/Heading'
import { toArabicNumerals } from '@/shared/utils/arabic'
import styles from './PrivacyPolicyView.module.scss'

const lastUpdated = toArabicNumerals('2025-08-18')

export default function PrivacyPolicyView() {
  return (
    <Page>
      <Heading className="mb-4" title="سياسة الخصوصية" subtitle="نلتزم بحماية خصوصيتك وشرح كيفية تعاملنا مع بياناتك" />

      <div className={styles.content}>
        <p className="lead">
          نُقدّم تطبيق «رفيق» كخدمة مجانية ومفتوحة المصدر للمستخدمين. تهدف هذه السياسة إلى توضيح كيفية جمع البيانات
          واستخدامها والاحتفاظ بها ومشاركتها عند استخدامك للتطبيق.
        </p>

        <h2 className="h4 mt-4">١. البيانات التي نجمعها</h2>
        <ul>
          <li>
            <strong>الموقع الجغرافي (اختياري):</strong>
            نستخدم <span dir="ltr">navigator.geolocation</span> — بعد موافقتك — للحصول على موقعك التقريبي لحساب مواقيت
            الصلاة. تتم هذه العملية على جهازك محليًا ولا نُرسل إحداثيات موقعك إلى خادم مملوك لنا.
          </li>
          <li>
            <strong>إعدادات محلية على جهازك:</strong>
            نخزن بعض التفضيلات مثل وضع الواجهة (فاتح/داكن) وإعدادات الإشعارات باستخدام
            <span dir="ltr">localStorage</span> على جهازك فقط.
          </li>
        </ul>

        <h2 className="h4 mt-4">٢. كيف نستخدم البيانات</h2>
        <ul>
          <li>حساب مواقيت الصلاة وعرض المحتوى المناسب لبلدك أو مدينتك (باستخدام الموقع الجغرافي على جهازك).</li>
          <li>تذكيرك بالأذكار عبر إشعارات محلية على جهازك بعد منح الإذن.</li>
          <li>تحسين الأداء وتجربة الاستخدام بالاستفادة من بيانات التحليلات المجمّعة.</li>
        </ul>

        <h2 className="h4 mt-4">٣. الإشعارات</h2>
        <p>
          يستخدم التطبيق واجهة إشعارات المتصفح/النظام بعد طلب إذنك الصريح. قد يُجدول التطبيق إشعارات للأذكار (صباحًا
          ومساءً) محليًا على جهازك. يمكنك التحكم بهذه الإشعارات أو إيقافها من إعدادات التطبيق أو إعدادات النظام.
        </p>

        <h2 className="h4 mt-4">٤. الجهات الخارجية والخدمات المستخدمة</h2>
        <ul>
          <li>
            <strong>مواقيت الصلاة:</strong>
            قد يعتمد التطبيق على واجهة برمجية مثل
            <a href="https://aladhan.com/prayer-times-api" target="_blank" rel="noopener noreferrer">
              Aladhan API
            </a>
            لجلب مواقيت الصلاة. تُرسل هذه الطلبات المعلومات اللازمة فقط (مثل المدينة/المعادلات الحسابية) ولا نربطها
            بهويتك.
          </li>
          <li>
            <strong>إذاعات القرآن الكريم:</strong>
            يستخدم التطبيق مصادر عامة مثل
            <a href="https://api.mp3quran.net/radios/radio_arabic.json" target="_blank" rel="noopener noreferrer">
              MP3Quran
            </a>
            لجلب بيانات محطات الإذاعة.
          </li>
        </ul>

        <h2 className="h4 mt-4">٥. تخزين البيانات والاحتفاظ بها</h2>
        <ul>
          <li>لا نخزن بيانات شخصية على خوادمنا. تبقى تفضيلاتك على جهازك المحلي.</li>
          <li>تحتفظ خدمات التحليلات التابعة لجهات خارجية ببيانات الاستخدام وفق سياساتها الخاصة.</li>
        </ul>

        <h2 className="h4 mt-4">٦. مشاركة البيانات</h2>
        <p>لا نبيع أو نتاجر في بياناتك. قد تتم مشاركة بيانات الاستخدام المجمّعة مع مزودي الخدمات بغرض تحسين التطبيق.</p>

        <h2 className="h4 mt-4">٧. أمان المعلومات</h2>
        <p>نبذل جهدًا معقولًا لحماية بياناتك. لكن لا توجد وسيلة نقل أو تخزين عبر الإنترنت آمنة بنسبة ١٠٠%.</p>

        <h2 className="h4 mt-4">٨. خصوصية الأطفال</h2>
        <p>لا يستهدف التطبيق الأطفال دون سن ١٣ عامًا بصفة خاصة ولا يجمع عن قصد معلومات شخصية منهم.</p>

        <h2 className="h4 mt-4">٩. حقوقك</h2>
        <ul>
          <li>يمكنك سحب الإذن بالموقع الجغرافي أو الإشعارات من إعدادات المتصفح/النظام.</li>
          <li>
            يمكنك حذف بيانات التفضيلات من المتصفح عبر مسح بيانات الموقع أو <span dir="ltr">localStorage</span>.
          </li>
        </ul>

        <h2 className="h4 mt-4">١٠. التغييرات على هذه السياسة</h2>
        <p>قد نقوم بتحديث هذه السياسة من حين لآخر. سنُحدّث تاريخ «آخر تحديث» أدناه عند حدوث أي تغيير جوهري.</p>

        <h2 className="h4 mt-4">١١. التواصل</h2>
        <p>
          لأي استفسار حول الخصوصية، يُرجى فتح تذكرة عبر
          <a href="https://github.com/AbdelrhmanSaid/rafeeq/issues" target="_blank" rel="noopener noreferrer">
            صفحة المشاكل على GitHub
          </a>
          .
        </p>

        <p className="text-muted mt-4">آخر تحديث: {lastUpdated}</p>
      </div>
    </Page>
  )
}

// src/app/views/PrivacyPolicyView.vue
<script setup>
import Page from '@/layout/Page.vue'
import Heading from '@/shared/ui/Heading.vue'
import { toArabicNumerals } from '@/shared/utils/arabic'

const lastUpdated = toArabicNumerals('2025-08-18')
</script>

<template>
  <Page>
    <Heading class="mb-4" title="سياسة الخصوصية" subtitle="نلتزم بحماية خصوصيتك وشرح كيفية تعاملنا مع بياناتك" />

    <div class="content">
      <p class="lead">
        نُقدّم تطبيق «رفيق» كخدمة مجانية ومفتوحة المصدر للمستخدمين. تهدف هذه السياسة إلى توضيح كيفية جمع البيانات
        واستخدامها والاحتفاظ بها ومشاركتها عند استخدامك للتطبيق.
      </p>

      <h2 class="h4 mt-4">١. البيانات التي نجمعها</h2>
      <ul>
        <li>
          <strong>الموقع الجغرافي (اختياري):</strong>
          نستخدم <span dir="ltr">navigator.geolocation</span> — بعد موافقتك — للحصول على موقعك التقريبي لحساب مواقيت
          الصلاة. تتم هذه العملية على جهازك محليًا ولا نُرسل إحداثيات موقعك إلى خادم مملوك لنا.
        </li>
        <li>
          <strong>إعدادات محلية على جهازك:</strong>
          نخزن بعض التفضيلات مثل وضع الواجهة (فاتح/داكن) وإعدادات الإشعارات باستخدام
          <span dir="ltr">localStorage</span> على جهازك فقط.
        </li>
      </ul>

      <h2 class="h4 mt-4">٢. كيف نستخدم البيانات</h2>
      <ul>
        <li>حساب مواقيت الصلاة وعرض المحتوى المناسب لبلدك أو مدينتك (باستخدام الموقع الجغرافي على جهازك).</li>
        <li>تذكيرك بالأذكار عبر إشعارات محلية على جهازك بعد منح الإذن.</li>
        <li>تحسين الأداء وتجربة الاستخدام بالاستفادة من بيانات التحليلات المجمّعة.</li>
      </ul>

      <h2 class="h4 mt-4">٣. الإشعارات</h2>
      <p>
        يستخدم التطبيق واجهة إشعارات المتصفح/النظام بعد طلب إذنك الصريح. قد يُجدول التطبيق إشعارات للأذكار (صباحًا
        ومساءً) محليًا على جهازك. يمكنك التحكم بهذه الإشعارات أو إيقافها من إعدادات التطبيق أو إعدادات النظام.
      </p>

      <h2 class="h4 mt-4">٤. الجهات الخارجية والخدمات المستخدمة</h2>
      <ul>
        <li>
          <strong>مواقيت الصلاة:</strong>
          قد يعتمد التطبيق على واجهة برمجية مثل
          <a href="https://aladhan.com/prayer-times-api" target="_blank" rel="noopener">Aladhan API</a>
          لجلب مواقيت الصلاة. تُرسل هذه الطلبات المعلومات اللازمة فقط (مثل المدينة/المعادلات الحسابية) ولا نربطها
          بهويتك.
        </li>
        <li>
          <strong>إذاعات القرآن الكريم:</strong>
          يستخدم التطبيق مصادر عامة مثل
          <a href="https://api.mp3quran.net/radios/radio_arabic.json" target="_blank" rel="noopener">MP3Quran</a>
          لجلب بيانات محطات الإذاعة.
        </li>
      </ul>

      <h2 class="h4 mt-4">٥. تخزين البيانات والاحتفاظ بها</h2>
      <ul>
        <li>لا نخزن بيانات شخصية على خوادمنا. تبقى تفضيلاتك على جهازك المحلي.</li>
        <li>تحتفظ خدمات التحليلات التابعة لجهات خارجية ببيانات الاستخدام وفق سياساتها الخاصة.</li>
      </ul>

      <h2 class="h4 mt-4">٦. مشاركة البيانات</h2>
      <p>لا نبيع أو نتاجر في بياناتك. قد تتم مشاركة بيانات الاستخدام المجمّعة مع مزودي الخدمات بغرض تحسين التطبيق.</p>

      <h2 class="h4 mt-4">٧. أمان المعلومات</h2>
      <p>نبذل جهدًا معقولًا لحماية بياناتك. لكن لا توجد وسيلة نقل أو تخزين عبر الإنترنت آمنة بنسبة ١٠٠%.</p>

      <h2 class="h4 mt-4">٨. خصوصية الأطفال</h2>
      <p>لا يستهدف التطبيق الأطفال دون سن ١٣ عامًا بصفة خاصة ولا يجمع عن قصد معلومات شخصية منهم.</p>

      <h2 class="h4 mt-4">٩. حقوقك</h2>
      <ul>
        <li>يمكنك سحب الإذن بالموقع الجغرافي أو الإشعارات من إعدادات المتصفح/النظام.</li>
        <li>يمكنك حذف بيانات التفضيلات من المتصفح عبر مسح بيانات الموقع أو <span dir="ltr">localStorage</span>.</li>
      </ul>

      <h2 class="h4 mt-4">١٠. التغييرات على هذه السياسة</h2>
      <p>قد نقوم بتحديث هذه السياسة من حين لآخر. سنُحدّث تاريخ "آخر تحديث" أدناه عند حدوث أي تغيير جوهري.</p>

      <h2 class="h4 mt-4">١١. التواصل</h2>
      <p>
        لأي استفسار حول الخصوصية، يُرجى فتح تذكرة عبر
        <a href="https://github.com/AbdelrhmanSaid/rafeeq/issues" target="_blank" rel="noopener"
          >صفحة المشاكل على GitHub</a
        >.
      </p>

      <p class="text-muted mt-4">آخر تحديث: {{ lastUpdated }}</p>
    </div>
  </Page>
</template>

<style scoped>
.content ul {
  padding-right: 1rem;
}
.content li + li {
  margin-top: 0.5rem;
}
</style>
